'use strict';
/* ============ INK STRIKE · game: player, combat, rounds, HUD, loop ============ */
const $ = id => document.getElementById(id);
const G = { state: 'menu', mode: 'comp', diff: 1, team: 'blue', ents: [], bots: [], player: null, now: 0, timescale: 1, score: { red: 0, blue: 0 }, round: 0, timer: 0, huntAll: false, paused: false,
  keys: {}, fire: false, alt: false, altEdge: false, fireEdge: false, mdx: 0, mdy: 0, buyOpen: false, shake: 0, nades: [], feed: [], dmgDirs: [], hitT: 0, hitKill: false, splats: [], lossStreak: { red: 0, blue: 0 },
  set: Object.assign({ sens: 1, fov: 84, vol: .7, xh: 'ink', xhStatic: 0, xhSize: 1, quality: 'balanced', motion: .35, inkFx: .5, lastBuy: [], map: 'papertown', aimMode: /Mac/.test(navigator.platform) ? 'trackpad' : 'mouse', actorStyle: 'scribe', battleSize: 'auto', autoTeamSize: null }, JSON.parse(localStorage.getItem('inkstrike') || '{}')), mapOpen: false, teamSize: 8, perf: { samples: [], cpu: [], pending: null, p90: 0, ms: 0, elapsed: 0 }, noLock: location.search.includes('auto') };
const WIN_ROUNDS = 7, ROUND_TIME = 110, FREEZE = 6, DM_TIME = 480, DM_KILLS = 40;
let renderer, scene, camera, fxc, fxg, radar, rg;

function boot() {
  const q = new URLSearchParams(location.search); if (['comp','dm','range'].includes(q.get('mode'))) G.mode = q.get('mode'); if (['blue','red'].includes(q.get('team'))) G.team = q.get('team'); if (q.has('diff') && [0,1,2].includes(+q.get('diff'))) G.diff = +q.get('diff');
  THREE.ColorManagement.enabled = false;
  renderer = new THREE.WebGLRenderer({ canvas: $('c'), antialias: true, powerPreference: 'high-performance' }); renderer.outputColorSpace = THREE.LinearSRGBColorSpace;
  renderer.autoClear = false; renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setClearColor(PAPER);
  scene = new THREE.Scene(); scene.fog = new THREE.FogExp2(PAPER, FOG_D); camera = new THREE.PerspectiveCamera(G.set.fov, 1, .06, 1400); camera.rotation.order = 'YXZ';
  fxc = $('fx'); fxg = fxc.getContext('2d'); radar = $('radar'); rg = radar.getContext('2d');
  G.set.map = new URLSearchParams(location.search).get('map') || G.set.map; buildMap(scene, G.set.map); FX.init(scene); bombInit(scene); VM.init(1); bindInput(); bindUI(); PROG.bind(); if ((('ontouchstart' in window || navigator.maxTouchPoints > 0) && matchMedia('(pointer: coarse)').matches) || location.search.includes('touch')) initTouch();
  makeIcons(); if (typeof makeActorPreviews === 'function') G.actorPreviews = makeActorPreviews(renderer); updateActorPreview(); applyQuality(); updateBrief(); onResize(); addEventListener('resize', onResize);
  camera.position.set(-20, 26, 62); camera.lookAt(6, 0, -6);
  $('loading').style.display = 'none'; $('menu').classList.add('on');
  let last = performance.now(); const loop = t => { requestAnimationFrame(loop); const elapsed = t - last, dt = Math.min(.05, elapsed / 1000); last = t; const at = performance.now(); if (!G.manualStep) frame(dt); samplePerformance(elapsed, performance.now() - at); }; requestAnimationFrame(loop);
}
function applyQuality() { renderer.setPixelRatio(Math.min(devicePixelRatio, ({ low: 1, balanced: 1.5, high: 2 })[G.set.quality] || 1.5)); MAP.setDetail(G.set.quality); if (camera && VM.cam) onResize(); }
function onResize() { const w = innerWidth, h = innerHeight; renderer.setSize(w, h); camera.aspect = VM.cam.aspect = w / h; camera.updateProjectionMatrix(); VM.cam.updateProjectionMatrix(); G.fxDpr = Math.min(2, window.devicePixelRatio || 1); fxc.width = Math.round(w * G.fxDpr); fxc.height = Math.round(h * G.fxDpr); for (const m of LINE_MATS) m.resolution.set(w, h); }
function makeIcons() {
  const s = new THREE.Scene(), cam = new THREE.OrthographicCamera(-.66, .66, .24, -.24, .1, 20), fm = fillMat({ objSpace: true, freq: 75, fog: 0, hatch: .8, hw: .13 }), lm = lineMat({ width: 1.6, fog: false }); cam.position.set(5, 0, 0); cam.lookAt(0, 0, 0);
  renderer.setPixelRatio(1); renderer.setSize(330, 120, false); lm.resolution.set(330, 120); G.icons = {};
  for (const k in GUNS) { const g = worldGun(k, fm, lm); g.traverse(o => o.frustumCulled = false); const bb = new THREE.Box3().setFromObject(g.children[0]), c = bb.getCenter(new V3()), hw = Math.max(.2, (bb.max.z - bb.min.z) / 2 * 1.12, (bb.max.y - bb.min.y) / 2 * 1.12 * 2.75);
    g.position.set(0, -c.y, -c.z); cam.left = -hw; cam.right = hw; cam.top = hw / 2.75; cam.bottom = -hw / 2.75; cam.updateProjectionMatrix();
    s.add(g); renderer.setClearColor(PAPER, 0); renderer.clear(); renderer.render(s, cam); G.icons[k] = renderer.domElement.toDataURL(); s.remove(g); }
  renderer.setClearColor(PAPER, 1); renderer.setPixelRatio(Math.min(devicePixelRatio, TOUCH.on ? 1.5 : 2));
}

/* ---------------- input ---------------- */
function bindInput() {
  addEventListener('keydown', e => { if (e.code === 'Escape') { for (const id of ['looks', 'armory']) if ($(id).classList.contains('on')) { $(id).classList.remove('on'); e.preventDefault(); return; } if (G.mapOpen) return toggleMap(false); if (G.buyOpen) return closeBuy(); if (G.state !== 'menu' && G.state !== 'matchEnd' && (G.noLock || G.paused || !document.pointerLockElement)) { setPause(!G.paused); return; } } if (['INPUT', 'SELECT'].includes(e.target.tagName)) return; if (e.code === 'Tab' || (G.state !== 'menu' && ['Space', 'ControlLeft', 'KeyF', 'KeyE'].includes(e.code))) e.preventDefault(); if (e.repeat) return; if (G.paused || G.buyOpen || G.mapOpen) { onKey(e.code); return; } G.keys[e.code] = true; onKey(e.code); });
  addEventListener('keyup', e => { G.keys[e.code] = false; if (e.code === 'KeyZ') G.fire = false; if (e.code === 'KeyV') G.alt = false; if (e.code === 'Tab') $('board').classList.remove('on'); });
  addEventListener('mousemove', mouseLook); addEventListener('mouseout', e => { if (!e.relatedTarget) resetLook(); });
  addEventListener('mousedown', e => { if (e.target.closest && e.target.closest('button,input,select,.ov')) return; if (G.player && !G.player.alive && G.mode === 'comp' && !G.paused && !G.mapOpen) { cycleSpectator(e.button === 2 ? -1 : 1); return; } if (!locked()) { if (e.target === renderer.domElement && G.state !== 'menu' && !G.paused) lock(); return; } if (e.button === 0) { G.fire = true; G.fireEdge = true; } if (e.button === 2) { G.alt = true; G.altEdge = true; } });
  addEventListener('mouseup', e => { if (e.button === 0) G.fire = false; if (e.button === 2) G.alt = false; });
  addEventListener('contextmenu', e => e.preventDefault());
  addEventListener('wheel', e => { if (!locked() || !G.player || !G.player.alive || G.set.aimMode === 'trackpad' || Math.abs(e.deltaY) < 12 || performance.now() < (G.wheelAt || 0)) return; G.wheelAt = performance.now() + 180; const pl = G.player, order = weaponOrder(pl), i = order.indexOf(pl.cur); switchTo(order[(i + (e.deltaY > 0 ? 1 : order.length - 1)) % order.length]); }, { passive: true });
  document.addEventListener('pointerlockchange', () => { resetLook(); if (!document.pointerLockElement && G.state !== 'menu' && G.state !== 'matchEnd' && !G.noLock && !G.buyOpen && !G.mapOpen && !G.uiUnlock) setPause(true); });
}
const locked = () => !G.paused && !G.buyOpen && !G.mapOpen && G.state !== 'menu' && G.state !== 'matchEnd' && (G.noLock || document.pointerLockElement === renderer.domElement);
function lock(recover = false) { if (G.noLock || TOUCH.on || G.lockPending || document.pointerLockElement === renderer.domElement) return; const el = renderer.domElement, fail = e => { if (recover || e && ['NotAllowedError', 'AbortError'].includes(e.name)) { $('captureMouse').textContent = '点击继续鼠标控制'; return; } G.noLock = true; banner('鼠标未锁定', '当前环境不支持指针锁定 · 建议用 Chrome / Safari 直接打开以获得完整操控', 'lose'); };
  const request = raw => { try { const p = raw ? el.requestPointerLock({ unadjustedMovement: G.set.aimMode !== 'trackpad' }) : el.requestPointerLock(); if (p && p.then) { G.lockPending = true; p.then(() => { G.lockPending = false; }, e => { G.lockPending = false; if (raw && e.name === 'NotSupportedError') request(false); else fail(e); }); } } catch (e) { G.lockPending = false; fail(e); } }; request(true); }

function clearInput() { resetLook(); G.fire = G.alt = G.fireEdge = G.altEdge = false; G.keys = {}; G.mdx = G.mdy = 0; if (TOUCH.on) touchReset(); }
function unlockUI() { if (document.pointerLockElement) { G.uiUnlock = true; document.exitPointerLock(); setTimeout(() => G.uiUnlock = false, 100); } clearInput(); }
function setPause(v) { G.paused = v; $('pause').classList.toggle('on', v); clearInput(); if (v) { G.mapOpen = false; $('tactical').classList.remove('on'); G.buyOpen = false; $('buy').classList.remove('on'); unlockUI(); } else lock(); }
function onKey(c) {
  if (c === 'KeyM' && !G.paused) { toggleMap(); return; } const pl = G.player; if (G.state === 'menu' || !pl || G.paused || G.mapOpen) return;
  if (c === 'Tab') { drawBoard(); $('board').classList.add('on'); return; }
  if (c === 'KeyB') { toggleBuy(); return; }
  if (G.buyOpen) { const n = c === 'Digit0' ? 10 : +c.replace('Digit', ''); if (n >= 1 && n <= BUY_LIST.length) buy(BUY_LIST[n - 1]); return; }
  if (!pl.alive) { if (c === 'ArrowLeft') cycleSpectator(-1); if (c === 'ArrowRight' || c === 'Space') cycleSpectator(1); return; }
  if (c === 'KeyZ') { G.fire = G.fireEdge = true; return; } if (c === 'KeyV') { G.alt = G.altEdge = true; return; }
  if (c === 'KeyT' && G.mode === 'range') return TRAIN.reset(true); if (c === 'KeyY' && G.mode === 'range') return TRAIN.setMoving(!TRAIN.moving); if (c === 'KeyG') return passCoreFeedback();
  if (c === 'Digit1' && pl.inv[1]) switchTo(pl.inv[1]); else if (c === 'Digit2' && pl.inv[2]) switchTo(pl.inv[2]); else if (c === 'Digit3') switchTo('knife'); else if (c === 'Digit4') { const l = nadeList(pl); if (l.length) switchTo(l[(l.indexOf(pl.cur) + 1) % l.length]); } else if (c === 'KeyX' && G.mode === 'range') { FX.clearDecals(); SFX.ui(); }
  else if (c === 'KeyQ' && pl.last && hasWeapon(pl.last)) switchTo(pl.last); else if (c === 'KeyR') startReload(); else if (c === 'KeyF' && pl.reloadEnd < 0) VM.insp = 0;
}
const NADES = ['he', 'flash', 'smoke'], nadeList = pl => NADES.filter(k => pl.nades[k] > 0), weaponOrder = pl => [pl.inv[1], pl.inv[2], 'knife', ...nadeList(pl)].filter(Boolean);
const hasWeapon = k => { const pl = G.player; return k === 'knife' || pl.inv[1] === k || pl.inv[2] === k || (WEAPONS[k].nade && pl.nades[k] > 0); };

/* ---------------- player ---------------- */
function makePlayer(team) { const p = makeEnt(team, '你', true); Object.assign(p, { inv: { 1: null, 2: 'p9' }, ammo: {}, cur: 'p9', last: 'knife', nades: { he: 0, flash: 0, smoke: 0 }, landSlow: 0, act: null, nextFire: 0, reloadEnd: -1, reloadStart: 0, drawEnd: 0, shots: 0, lastShot: -9, recP: 0, recY: 0, recTP: 0, recTY: 0, punch: 0, roll: 0, scoped: 0, bobPhase: 0, pending: null, deathT: 0 }); return p; }
function giveWeapon(pl, k) { const w = WEAPONS[k]; if (w.nade) { pl.nades[k] = 1; return; } pl.inv[w.slot] = k; pl.ammo[k] = { mag: w.mag, res: w.res }; }
function switchTo(k) { const pl = G.player; if (!k || k === pl.cur && VM.key === k) return; if (k !== pl.cur) pl.last = pl.cur; pl.cur = k; pl.weapon = k; VM.show(k); pl.drawEnd = G.now + WEAPONS[k].draw; pl.reloadEnd = -1; pl.scoped = 0; pl.shots = 0; pl.pending = null; SFX.click(700, .25); }
function startReload() { const pl = G.player, w = WEAPONS[pl.cur], a = pl.ammo[pl.cur]; if (!a || pl.reloadEnd >= 0 || a.mag >= w.mag || a.res <= 0 || G.now < pl.drawEnd) return; pl.reloadStart = G.now; pl.reloadEnd = G.now + w.reload; pl.scoped = 0; VM.insp = 1; if (w.pump) { for (let i = 0; i < 5; i++) SFX.shellIn(w.reload * (.12 + i * .16)); SFX.pump(w.reload * .9); } else SFX.reload(w.snd, w.reload); }
function updatePlayer(dt) {
  const pl = G.player, now = G.now, k = G.keys, w = WEAPONS[pl.cur], frozen = G.state !== 'live';
  const wantC = (k.KeyC || k.ControlLeft) ? 1 : 0; let tc = wantC; if (!wantC && pl.crouchAmt > .05) { const h = pl.hgt; pl.hgt = 1.8; if (entOverlap(pl, pl.pos.x, pl.pos.y, pl.pos.z, MAP.near(pl.pos.x, pl.pos.z))) tc = 1; pl.hgt = h; }
  const oh = pl.hgt; pl.crouchAmt = damp(pl.crouchAmt, tc, 13, dt); pl.hgt = 1.8 - .45 * pl.crouchAmt; if (!pl.onGround) pl.pos.y += oh - pl.hgt;   // crouch-jump: tuck the legs up
  let f = (k.KeyW ? 1 : 0) - (k.KeyS ? 1 : 0), s = (k.KeyD ? 1 : 0) - (k.KeyA ? 1 : 0), an = 1; if (TOUCH.on && (TOUCH.move.x || TOUCH.move.y)) { f = -TOUCH.move.y; s = TOUCH.move.x; an = clamp((Math.hypot(f, s) - .12) / .78, 0, 1); } if (frozen || pl.act || G.buyOpen || G.mapOpen) f = s = 0;
  let wx = -Math.sin(pl.yaw) * f + Math.cos(pl.yaw) * s, wz = -Math.cos(pl.yaw) * f - Math.sin(pl.yaw) * s; const wl = Math.hypot(wx, wz); if (wl > 0) { wx /= wl; wz /= wl; }
  const walking = k.ShiftLeft || k.ShiftRight || an < .62, sp = 5.1 * an * w.speed * (pl.crouchAmt > .5 ? .45 : (k.ShiftLeft || k.ShiftRight) ? .52 : 1) * (pl.scoped ? .55 : 1) * (pl.landSlow > 0 ? .58 : 1); pl.landSlow -= dt;
  const lad = !frozen && now > (pl.ladCd || 0) && ladderAt(pl.pos), lup = f > .3 ? (pl.pitch > -.4 ? 1 : -1) : f < -.3 ? -1 : 0;
  if (lad && (lup !== 0 || pl.pos.y > lad.y1 + .15) && !(lup < 0 && pl.onGround)) { if (k.Space) { pl.ladCd = now + .45; pl.vel.y = 3.5; pl.vel.x += Math.sin(pl.yaw) * 2.5; pl.vel.z += Math.cos(pl.yaw) * 2.5; } else { pl.onGround = false; pl.vel.y = (lup > 0 && pl.pos.y >= lad.y2 ? 0 : lup * 3.4) + GRAV * dt; if (pl.pos.y < lad.y2 - .1) { pl.vel.x *= .7; pl.vel.z *= .7; } pl.stepAcc += Math.abs(lup) * 3.4 * dt; if (pl.stepAcc > 1.1) { pl.stepAcc = 0; SFX.step(null, .2, 'metal'); } } }
  if (k.Space && pl.onGround && !frozen) { pl.vel.y = 5.95; pl.onGround = false; SFX.step(null, .2); }
  groundMove(pl, wx, wz, wl ? sp : 0, dt, 14, 9);
  const hs = Math.hypot(pl.vel.x, pl.vel.z), cap = 5.1 * 1.55; if (hs > cap) { pl.vel.x *= cap / hs; pl.vel.z *= cap / hs; }
  const px = pl.pos.x, pz = pl.pos.z; moveEntity(pl, dt);
  if (pl.landed > 2.6) { pl.landSlow = .3; pl.vel.x *= .6; pl.vel.z *= .6; }   // landing penalty: kills endless bunny-hopping
  if (pl.landed > 4) { VM.dip = Math.min(.06, pl.landed * .005); pl.punch += pl.landed * .004; SFX.land(null); if (pl.landed > 12.5) hurt(pl, Math.round((pl.landed - 12.5) * 9), null, null, 'legs', null); botHear(pl.pos, pl.team, 14, 'step'); }
  pl.stepSmooth = clamp(pl.stepSmooth, -.6, .6); pl.stepSmooth = damp(pl.stepSmooth, 0, 13, dt);
  const moved = Math.hypot(pl.pos.x - px, pl.pos.z - pz); if (pl.onGround) { pl.bobPhase += moved * 2.0; if (hs > 3 && !walking) { pl.stepAcc += moved; if (pl.stepAcc > 2.1) { pl.stepAcc = 0; SFX.step(null, .22, surfaceAt(pl.pos)); botHear(pl.pos, pl.team, 11, 'step'); } } }
  // ---- weapon ----
  if (pl.reloadEnd >= 0) { VM.reloadT = clamp((now - pl.reloadStart) / w.reload, 0, 1); if (now >= pl.reloadEnd) { const a = pl.ammo[pl.cur], n = Math.min(w.mag - a.mag, a.res); a.mag += n; a.res -= n; pl.reloadEnd = -1; VM.reloadT = -1; } } else VM.reloadT = -1;
  if (now - pl.lastShot > .32) pl.shots = 0;
  if (now - pl.lastShot > .1) { pl.recTP = damp(pl.recTP, 0, 7, dt); pl.recTY = damp(pl.recTY, 0, 7, dt); }
  pl.recP = damp(pl.recP, pl.recTP, 30, dt); pl.recY = damp(pl.recY, pl.recTY, 30, dt); pl.punch = damp(pl.punch, 0, 9, dt); pl.roll = damp(pl.roll, -s * .012, 8, dt);
  const ready = now >= pl.drawEnd && pl.reloadEnd < 0 && !frozen && !G.buyOpen && !G.mapOpen && !pl.act;
  if (frozen) pl.pending = null; if (pl.pending && now >= pl.pending.t) { pl.pending.fn(); pl.pending = null; }
  if ((w.scope || w.optic) && G.altEdge && ready) { pl.scoped = (pl.scoped + 1) % (w.scope ? 3 : 2); pl.scopeSince = now; SFX.click(1200, .2); }
  if (ready && now >= pl.nextFire) {
    if (w.melee) { if (G.fire || G.alt) { const heavy = !G.fire; pl.nextFire = now + (heavy ? w.rate2 : w.rate); VM.atk = 0; VM.atkKind = heavy ? 1 : 0; SFX.swish(); pl.pending = { t: now + (heavy ? .16 : .09), fn: () => melee(pl, heavy ? w.dmg2 : w.dmg) }; } }
    else if (w.nade) { const kind = pl.cur; if (G.fireEdge && pl.nades[kind] > 0) { pl.nextFire = now + 1; VM.atk = 0; SFX.swish(); pl.pending = { t: now + .2, fn: () => { throwNade(pl, kind); pl.nades[kind]--; if (G.mode === 'range') pl.nades[kind] = 1; if (pl.nades[kind] <= 0) switchTo(nadeList(pl)[0] || pl.inv[1] || pl.inv[2]); } }; } }
    else if ((w.auto ? G.fire : G.fireEdge)) { const a = pl.ammo[pl.cur]; if (a.mag > 0) playerFire(pl, w, a); else { if (G.fireEdge) SFX.click(1600, .25); if (a.res > 0) startReload(); } }
  }
  if (pl.ammo[pl.cur] && pl.ammo[pl.cur].mag === 0 && pl.ammo[pl.cur].res > 0 && pl.reloadEnd < 0 && now > pl.nextFire && ready) startReload();
  pl.spread = curSpread(pl, w);
}
function curSpread(pl, w) { if (w.melee || w.nade) return .004; const sf = Math.hypot(pl.vel.x, pl.vel.z) / (5.1 * w.speed), settle = w.scope && pl.scoped ? clamp((G.now - (pl.scopeSince ?? -9)) / .38, 0, 1) : 1; let s = w.spread + (w.scope && !pl.scoped ? w.noScope : 0) + (sf > (w.scope ? .12 : .36) ? sf * sf * w.moveSp : 0) + (1 - settle) * .032 + (pl.onGround ? 0 : .08) + Math.min(pl.shots, 14) * w.sprayInc; if (pl.crouchAmt > .5) s *= .78; return w.pellets ? Math.max(w.spread, s) : s; }
const _cq = new THREE.Quaternion(), _ce = new THREE.Euler(0, 0, 0, 'YXZ'), _cv = new V3();
function playerFire(pl, w, a) {
  const now = G.now; pl.spawnProtectedUntil = 0; TRAIN.onShot(); a.mag--; pl.nextFire = now + w.rate; pl.lastShot = now; const ey = pl.pos.y + eyeY(pl) + pl.stepSmooth, sp = curSpread(pl, w), py = pl.pitch + pl.recP, yw = pl.yaw + pl.recY;
  _ce.set(py, yw, 0); _cq.setFromEuler(_ce); const mz = _cv.set(.12, -.09, -.75).applyQuaternion(_cq); const mx = pl.pos.x + mz.x, my = ey + mz.y, mzz = pl.pos.z + mz.z;
  fireWeaponVolley(pl, pl.pos.x, ey, pl.pos.z, py, yw, sp, w, mx, my, mzz, pl.scoped > 0);
  const n = ++pl.shots, c = pl.crouchAmt > .5 ? .8 : 1; const pt = w.pat[Math.min(n - 1, w.pat.length - 1)]; pl.recTP += pt[0] * c; pl.recTY += (pt[1] + gauss() * w.side * .05) * c; pl.recTP = Math.min(pl.recTP, .24);
  VM.fire(w); G.shake = Math.min(1, G.shake + w.vm * 1.6); SFX.shot(w.snd, null, isIndoor(pl)); if (w.scope) pl.scoped = 0; if (w.bolt) SFX.bolt(.32); else if (w.pump) SFX.pump(.28); if (!w.bolt && !w.pellets && (!w.auto || Math.random() < .35)) SFX.shellDrop(1);
  _cv.set(1.6 + rand(.8), 1.6 + rand(.8), -.3).applyQuaternion(_cq); if (!w.bolt) FX.shell(mx - mz.x * .5, my, mzz - mz.z * .5, _cv.x + pl.vel.x, _cv.y, _cv.z + pl.vel.z);
  botHear(pl.pos, pl.team, w.snd === 'm4' ? 22 : 55);
}
function melee(pl, dmg) { pl.spawnProtectedUntil = 0; const cp = Math.cos(pl.pitch), dx = -Math.sin(pl.yaw) * cp, dy = Math.sin(pl.pitch), dz = -Math.cos(pl.yaw) * cp, ey = pl.pos.y + eyeY(pl); let best = null, be = null;
  for (const e of G.ents) if (e.alive && e.team !== pl.team) { let r = rayEnt(pl.pos.x, ey, pl.pos.z, dx, dy, dz, e); if (r && r.t >= 2.1) r = null;
    if (!r) { const tx = e.pos.x - pl.pos.x, ty = e.pos.y + eyeY(e) * .72 - ey, tz = e.pos.z - pl.pos.z, d = Math.hypot(tx, ty, tz); if (d < 2.2 && (tx * dx + ty * dy + tz * dz) / (d || 1) > .84) r = { t: Math.max(.3, d - .3), part: 'chest' }; }   // forgiving swing cone: a blade is not a bullet
    if (r && (!best || r.t < best.t)) { best = r; be = e; } }
  const h = rayWorld(pl.pos.x, ey, pl.pos.z, dx, dy, dz, 2.0); if (be && (!h || h.t > best.t)) { const back = (-Math.sin(be.yaw) * dx - Math.cos(be.yaw) * dz) > .5; hurt(be, dmg * (back ? 3 : 1), pl, 'knife', 'chest', { x: dx, y: dy, z: dz }, { x: pl.pos.x + dx * best.t, y: ey + dy * best.t, z: pl.pos.z + dz * best.t }); G.shake += .15; }
  else if (h) { FX.decal(pl.pos.x + dx * h.t, ey + dy * h.t, pl.pos.z + dz * h.t, h.nx, h.ny, h.nz, .12, INK); SFX.impact(null); } }
function throwNade(e, kind = 'he') { e.spawnProtectedUntil = 0; const cp = Math.cos(e.pitch), dx = -Math.sin(e.yaw) * cp, dy = Math.sin(e.pitch), dz = -Math.cos(e.yaw) * cp; if (!G.nadeFm) { G.nadeFm = fillMat({ objSpace: true, freq: 60 }); }
  const m = worldGun(kind, G.nadeFm, ACTOR_LM); m.scale.setScalar(1.6); scene.add(m); G.nades.push({ owner: e, m, p: new V3(e.pos.x + dx * .5, e.pos.y + eyeY(e) - .05, e.pos.z + dz * .5), v: new V3(dx * 17 + e.vel.x * .6, dy * 17 + 3.2, dz * 17 + e.vel.z * .6), t: WEAPONS[kind].fuse, kind }); }
function updateNades(dt) { for (let i = G.nades.length - 1; i >= 0; i--) { const n = G.nades[i]; n.t -= dt; n.v.y -= GRAV * dt; const sp = n.v.length(), d = sp * dt;
    if (sp > .01) { const h = rayWorld(n.p.x, n.p.y, n.p.z, n.v.x / sp || 1e-9, n.v.y / sp || 1e-9, n.v.z / sp || 1e-9, d + .08); if (h) { const dot = n.v.x * h.nx + n.v.y * h.ny + n.v.z * h.nz; n.v.x -= 2 * dot * h.nx; n.v.y -= 2 * dot * h.ny; n.v.z -= 2 * dot * h.nz; n.v.multiplyScalar(.42); if (sp > 2) SFX.impact(n.p); if (h.ny > .5 && Math.abs(n.v.y) < 1) { n.v.y = 0; n.v.x *= .8; n.v.z *= .8; } } else n.p.addScaledVector(n.v, dt); }
    if (n.p.y < .08) { n.p.y = .08; if (n.v.y < 0) n.v.y = 0; } n.m.position.copy(n.p); n.m.rotation.x += dt * sp; n.m.rotation.z += dt * sp * .7;
    if (n.t <= 0 && n.kind !== 'he') { scene.remove(n.m); G.nades.splice(i, 1); n.kind === 'smoke' ? smokeSpawn(n.p.x, MAP.floorAt(n.p.x, n.p.z), n.p.z) : flashBang(n.p.x, n.p.y + .25, n.p.z); continue; }
    if (n.t <= 0) { scene.remove(n.m); G.nades.splice(i, 1); FX.explode(n.p.x, n.p.y, n.p.z); SFX.boom(n.p); const pd = G.player.pos.distanceTo(n.p); G.shake += clamp(1.4 - pd / 14, 0, 1.2);
      for (const e of G.ents) { if (!e.alive || (e.team === n.owner.team && e !== n.owner)) continue; const dd = Math.hypot(e.pos.x - n.p.x, e.pos.y + .9 - n.p.y, e.pos.z - n.p.z); if (dd > 7.5 || !segClear(n.p.x, n.p.y + .3, n.p.z, e.pos.x, e.pos.y + 1, e.pos.z)) continue;
        const dir = { x: (e.pos.x - n.p.x) / (dd || 1), y: .3, z: (e.pos.z - n.p.z) / (dd || 1) }; hurt(e, Math.round(105 * Math.pow(1 - dd / 7.5, 1.3)), n.owner, 'he', 'chest', dir, { x: e.pos.x, y: e.pos.y + 1, z: e.pos.z }); } } } }

const isIndoor = e => !!rayWorld(e.pos.x, e.pos.y + 1.7, e.pos.z, 1e-9, 1, 1e-9, 9);
/* ---------------- combat ---------------- */
function fireWeaponVolley(sh, ox, oy, oz, pitch, yaw, spread, w, mx, my, mz, noTracer) { for (let i = 0; i < (w.pellets || 1); i++) { const r = spread ? Math.abs(gauss()) * spread * .7 : 0, an = spread ? rand(6.2832) : 0, p = pitch + Math.sin(an) * r, y = yaw + Math.cos(an) * r, cp = Math.cos(p); fireBullet(sh, ox, oy, oz, -Math.sin(y) * cp, Math.sin(p), -Math.cos(y) * cp, w, mx, my, mz, noTracer); } }
function fireBullet(sh, ox, oy, oz, dx, dy, dz, w, mx, my, mz, noTracer) {
  const length = Math.hypot(dx, dy, dz), range = w.range || 260; if (length < 1e-8) return; dx /= length; dy /= length; dz /= length;
  if (w.bolt && typeof botOnShot === 'function') botOnShot(sh, sh.weapon, new V3(ox, oy, oz), new V3(dx, dy, dz));
  dx = dx || 1e-9; dy = dy || 1e-9; dz = dz || 1e-9; let best = null, be = null;
  for (const e of G.ents) { if (!e.alive || e.team === sh.team) continue; const r = rayEnt(ox, oy, oz, dx, dy, dz, e); if (r && r.t < range && (!best || r.t < best.t)) { best = r; be = e; } }
  let t0 = 0, mul = 1, endT = range, hitEnt = false;
  for (let pen = 0; pen < 2; pen++) { const h = rayWorld(ox + dx * t0, oy + dy * t0, oz + dz * t0, dx, dy, dz, range - t0); const wt = h ? t0 + h.t : range;
    if (best && best.t < wt && best.t >= t0) { hitEnt = true; endT = best.t; break; } endT = wt; if (!h) break;
    const ix = ox + dx * wt, iy = oy + dy * wt, iz = oz + dz * wt, nx = h.nx, ny = h.ny, nz = h.nz, thin = h.s && (h.tx - h.t) < .5, ex = t0 + h.tx;
    FX.decal(ix, iy, iz, nx, ny, nz, rand(.13, .24) * (w.dmg > 50 ? 1.5 : 1), INK); FX.burst(ix, iy, iz, nx, ny, nz, 4, INK, 2.5, .018); if (sh.isPlayer || Math.random() < .4) SFX.impact({ x: ix, y: iy, z: iz });
    if (thin && w.penetration !== 0 && pen === 0 && ex < range) { mul = w.penetration === undefined ? .55 : w.penetration; t0 = ex + .02; FX.decal(ox + dx * ex, oy + dy * ex, oz + dz * ex, -nx, -ny, -nz, .2, INK); FX.burst(ox + dx * ex, oy + dy * ex, oz + dz * ex, dx, dy, dz, 5, INK, 3, .02); continue; } break; }
  if (!noTracer || !sh.isPlayer) FX.tracer(mx, my, mz, ox + dx * endT, oy + dy * endT, oz + dz * endT);
  if (hitEnt) { const partMul = best.part === 'head' && w.headMult ? w.headMult : best.mul, dmg = w.dmg * partMul * mul * weaponFalloff(w, best.t); if (dmg > 0) hurt(be, dmg, sh, sh.weapon, best.part, { x: dx, y: dy, z: dz }, { x: ox + dx * best.t, y: oy + dy * best.t, z: oz + dz * best.t }); }
}
function hurt(e, dmg, by, wkey, part, dir, pt) {
  if (!e.alive || G.now < (e.spawnProtectedUntil || 0) || G.mode === 'comp' && G.state !== 'live' && by) return; const w = wkey ? WEAPONS[wkey] : null, head = part === 'head';
  if (w && e.armor > 0 && part !== 'legs' && (!head || e.helmet)) { const d2 = dmg * (w.arm || .6); e.armor = Math.max(0, e.armor - Math.max(2, dmg - d2)); dmg = d2; }   // armour visibly wears: it loses what it absorbs (min 2 per hit)
  dmg = Math.max(1, Math.round(dmg)); e.hp -= dmg; PROG.onHurt(e, Math.min(dmg, e.hp + dmg), by, wkey); if (by && by.isPlayer && e !== by) TRAIN.onHit(Math.min(dmg, e.hp + dmg), head, wkey); if (e.act && e.act.type === 'defuse' && !e.isPlayer && Math.random() < .5) { e.act = null; if (BOMB.defuser === e) BOMB.defuser = null; }
  if (pt && dir) { FX.burst(pt.x, pt.y, pt.z, dir.x, dir.y, dir.z, 6 + Math.min(16, dmg / 5 | 0), RED, 4.5, .03, true); FX.burst(pt.x, pt.y, pt.z, -dir.x, .3, -dir.z, 3, RED, 2, .025, true); SFX.flesh(e.isPlayer ? null : pt);
    const h = rayWorld(pt.x + dir.x * .4, pt.y + dir.y * .4, pt.z + dir.z * .4, dir.x + rand(-.15, .15) || 1e-9, dir.y - .12, dir.z + rand(-.15, .15) || 1e-9, 4.5); if (h) FX.decal(pt.x + dir.x * (.4 + h.t), pt.y + (dir.y - .12) * (.4 + h.t), pt.z + dir.z * (.4 + h.t), h.nx, h.ny, h.nz, rand(.35, .8) * (head ? 1.4 : 1), RED); }
  if (e.isPlayer) { SFX.hurt(); e.punch += .035 + dmg * .0012; G.shake += .25; if (by) G.dmgDirs.push({ x: by.pos.x, z: by.pos.z, t: 1.2 }); G.splats.push({ x: rand(.1, .9), y: rand(.1, .9), s: rand(60, 160) * (1 + dmg / 60), t: 1.6, r: rand(6) }); if (G.splats.length > 8) G.splats.shift(); }
  else { e.flinch = 1; e.model.fm.uniforms.uFlash.value = .85; }
  if (by && by.isPlayer && e !== by) { G.hitT = .22; G.hitKill = e.hp <= 0; head ? SFX.head() : SFX.hit(); if (pt) FX.num(pt, dmg, head); }
  if (e.hp <= 0) kill(e, by, wkey, head, dir);
}
function kill(e, by, wkey, head, dir) {
  e.alive = false; e.hp = 0; e.deaths++; e.spawnProtectedUntil = 0; if (G.mode === 'comp') { e.armor = 0; e.helmet = false; e.keep = false; e.weaponKeep = null; } e.deathT = 0; e.respawnT = G.now + 3; const fl = MAP.floorAt(e.pos.x, e.pos.z);
  if (by && by !== e) { by.kills++; if (G.mode === 'comp') by.money = Math.min(16000, by.money + (WEAPONS[wkey] ? WEAPONS[wkey].reward : 300)); if (G.mode === 'dm') G.score[by.team]++; }
  FX.decal(e.pos.x + rand(-.3, .3), Math.abs(e.pos.y - fl) < .4 ? fl : e.pos.y, e.pos.z + rand(-.3, .3), 0, 1, 0, rand(1.3, 2.1), RED, true); FX.burst(e.pos.x, e.pos.y + 1.2, e.pos.z, 0, 1, 0, 14, INK, 3.5, .03);
  addFeed(by, e, wkey, head); PROG.onKill(e, by, wkey); if (by && by.isPlayer) TRAIN.onKill(wkey); e.act = null;
  if (e.isPlayer) { e.scoped = 0; G.deathCam = { t: 0, yaw: e.yaw, by }; G.spec = null; if (G.mode === 'comp') unlockUI(); $('dead').classList.add('on'); $('deadBy').textContent = by && by !== e ? `被 ${by.name} 用 ${WEAPONS[wkey] ? WEAPONS[wkey].name : '环境'} 击倒` : '你倒下了'; if (G.mode === 'comp') { e.inv[1] = null; e.inv[2] = 'p9'; e.nades = { he: 0, flash: 0, smoke: 0 }; e.armor = 0; e.helmet = false; } closeBuy(); PROG.report('本次交战'); }
  else { const f = dir ? (-Math.sin(e.yaw) * dir.x - Math.cos(e.yaw) * dir.z) : -1; e.fallDir = f > 0 ? -1 : 1; e.target = null; e.model.mark.visible = false; }
  if (by && by.isPlayer && e !== by) { SFX.kill(); combatNotice(head ? '爆头击倒' : '击倒', G.mode === 'comp' && WEAPONS[wkey] ? `${e.name}  +$${WEAPONS[wkey].reward}` : e.name); }
  if (G.mode === 'comp' && G.state === 'live') checkRoundEnd();
  if (G.mode === 'dm' && G.state === 'live' && Math.max(G.score.red, G.score.blue) >= DM_KILLS) endMatch(G.score.red > G.score.blue ? 'red' : 'blue');
}
G.botShoot = (b, dx, dy, dz) => { b.spawnProtectedUntil = 0; const w = WEAPONS[b.weapon], ey = b.pos.y + eyeY(b), mx = b.pos.x + dx * .8 + Math.cos(b.yaw) * .13, my = ey - .12, mz = b.pos.z + dz * .8 - Math.sin(b.yaw) * .13;
  fireWeaponVolley(b, b.pos.x, ey, b.pos.z, Math.atan2(dy, Math.hypot(dx, dz)), Math.atan2(-dx, -dz), w.pellets ? w.spread : 0, w, mx, my, mz);
  FX.flash(mx, my, mz, .22); SFX.shot(w.snd, b.pos, isIndoor(b)); botHear(b.pos, b.team, 45); };

/* ---------------- match flow ---------------- */
function startMatch() {
  if (G.mode !== 'range') G.rangeTeam = null; else if (!G.rangeTeam) G.rangeTeam = G.team; for (const b of G.bots) disposeBotModel(b); for (const n of G.nades) scene.remove(n.m); G.nades = []; G.ents = []; G.bots = []; G.score = { red: 0, blue: 0 }; G.round = 0; G.lossStreak = { red: 0, blue: 0 }; G.feed = []; drawFeed();
  const pl = G.player = makePlayer(G.team); pl.money = G.mode === 'dm' ? 16000 : 800; G.ents.push(pl); giveWeapon(pl, 'p9');
  G.teamSize = G.set.battleSize === 'auto' ? clamp(G.perf.pending || G.set.autoTeamSize || (TOUCH.on ? 5 : 8), 5, 12) : Number(G.set.battleSize); if (![5, 8, 12].includes(G.teamSize)) G.teamSize = 8; G.perf.samples = []; G.perf.cpu = []; G.perf.elapsed = 0; G.perf.pending = null; G.botSerial = 0;
  if (G.mode === 'range') { pl.team = G.team = 'blue'; pl.money = 16000; for (let i = 0; i < RANGE_SPOTS.length; i++) { const b = makeBot('red', `靶 ${RANGE_SPOTS[i].d}m`, scene); b.dummy = true; b.rangeI = i; G.ents.push(b); G.bots.push(b); } }
  else for (const team of ['blue', 'red']) for (let i = 0; i < G.teamSize - (team === G.team ? 1 : 0); i++) addRosterBot(team, 800);
  G.paused = false; G.mapOpen = G.buyOpen = false; clearCombatFeedback(); for (const id of ['tactical', 'buy', 'pause']) $(id).classList.remove('on'); $('menu').classList.remove('on'); $('end').classList.remove('on'); $('hud').classList.add('on'); SFX.init(); SFX.setVol(G.set.vol); if (TOUCH.on) touchStartMatch(); lock(); startRound();
}
const RANGE_SPOTS = MAP.rangeSpots;
function spawnSafety(q, e) { const enemies = G.ents.filter(o => o !== e && o.alive && o.team !== e.team).map(o => ({ o, d: Math.hypot(o.pos.x - q.x, o.pos.z - q.z) })).sort((a, b) => a.d - b.d), near = enemies.length ? enemies[0].d : 40; let score = Math.min(40, near); for (const { o, d } of enemies.slice(0, 4)) if (d < 38 && segClear(q.x, q.y + 1.4, q.z, o.pos.x, o.pos.y + eyeY(o), o.pos.z)) score -= 22 * (1 - d / 60); for (const o of G.ents) if (o !== e && o.alive && Math.hypot(o.pos.x - q.x, o.pos.z - q.z) < 2) score -= 45; return score; }
function spawnEnt(e) {
  const restoreMouse = e.isPlayer && !!G.deathCam; let p; if (G.mode === 'range') p = e.isPlayer ? MAP.rangePlayer : { x: RANGE_SPOTS[e.rangeI].x, y: MAP.floorAt(RANGE_SPOTS[e.rangeI].x, RANGE_SPOTS[e.rangeI].z), z: RANGE_SPOTS[e.rangeI].z };
  else if (G.mode === 'dm' && G.round > 0 && G.state === 'live') { let best = -Infinity; for (let i = 0; i < 18; i++) { const q = navRandomIn({ x1: -58, x2: 58, z1: -50, z2: 50 }), score = spawnSafety(q, e); if (score > best) { best = score; p = q; } } }
  else { let best = -1; for (let i = 0; i < 20; i++) { const q = navRandomIn(MAP.spawn[e.team]); let d = 1e9; for (const o of G.ents) if (o !== e && o.alive) d = Math.min(d, Math.hypot(o.pos.x - q.x, o.pos.z - q.z)); if (d > best) { best = d; p = q; } if (d > 2.5) break; } }
  e.pos.set(p.x, p.y, p.z); e.vel.set(0, 0, 0); e.yaw = e.team === 'red' ? 0 : Math.PI; if (G.mode === 'dm') e.yaw = Math.atan2(p.x, p.z); if (G.mode === 'range') e.yaw = e.isPlayer ? Math.atan2(-(RANGE_SPOTS[0].x - p.x), -(RANGE_SPOTS[0].z - p.z)) : Math.atan2(-(MAP.rangePlayer.x - p.x), -(MAP.rangePlayer.z - p.z)); e.pitch = 0; e.act = null; e.blindT = 0; e.hp = 100; e.alive = true; e.onGround = true; e.crouchAmt = 0; e.hgt = 1.8; e.stepSmooth = 0; e.spottedBy = {}; e.spottedT = -9; e.spawnProtectedUntil = G.mode === 'dm' ? G.now + 1.25 : 0;
  if (e.isPlayer) { $('specControls').hidden = true; $('dead').classList.remove('on'); $('report').classList.remove('on'); G.deathCam = null; clearInput(); clearCombatFeedback(); e.pending = null; e.nextFire = 0; e.lastShot = -9; e.shots = 0; e.landSlow = 0; e.ladCd = 0; e.stepAcc = 0; e.punch = e.roll = 0; e.recP = e.recY = e.recTP = e.recTY = 0; for (const k in e.ammo) { const w = WEAPONS[k]; e.ammo[k] = { mag: w.mag, res: w.res }; } if (G.mode === 'dm') { e.armor = 100; e.helmet = true; } VM.key = null; switchTo(e.inv[1] || e.inv[2]); if (restoreMouse && !G.noLock && !document.pointerLockElement) lock(true); }
  else { const m = e.model; m.root.visible = true; m.root.rotation.x = 0; m.legL.rotation.x = m.legR.rotation.x = 0; m.mark.visible = e.team === G.team; e.target = null; e.targetVis = false; e.lastSeenT = e.lastVisualT = e.alertT = -9; e.nextFire = 0; e.burstPause = 0; e.burstN = 0; e.nadeCd = 0; e.path = null; e.waitT = 0; e.state = 'roam'; e.lookYaw = e.yaw; resetBotAwareness(e); botBuy(e); }
}
function botBuy(b) {
  if (b.dummy) { b.armor = b.rangeI % 2 ? 100 : 0; b.helmet = b.rangeI % 2 === 1; setEntWeapon(b, b.rangeI % 2 ? 'm4' : 'ak'); return; }
  b.nade = null; if (G.mode === 'dm' ? Math.random() < .3 : (b.money >= 2500 && Math.random() < .55)) { b.nade = pick(['he', 'flash', 'flash', 'smoke']); if (G.mode === 'comp') b.money -= WEAPONS[b.nade].price; }
  let k = b.keep && b.weaponKeep ? b.weaponKeep : 'p9';
  if (G.mode === 'dm') { k = pick(['ak', 'm4', 'viper', 'ak', 'm4', 'nova', 'awp']); b.armor = 100; b.helmet = true; }
  else { if (!b.keep || k === 'p9' || k === 'deagle') { const m = b.money, rifle = b.team === 'red' ? 'ak' : 'm4'; let pickK = null; if (m >= 5200 && Math.random() < .18) pickK = 'awp'; else if (m >= WEAPONS[rifle].price + 300) pickK = rifle; else if (m >= 2000) pickK = Math.random() < .7 ? 'viper' : 'nova'; else if (m >= 900 && Math.random() < .5) pickK = 'deagle';
      if (pickK) { b.money -= WEAPONS[pickK].price; k = pickK; } } if (b.armor < 50 && b.money >= 1000) { b.money -= 1000; b.armor = 100; b.helmet = true; } }
  setEntWeapon(b, k); b.keep = false;
}
function startRound() {
  clearInput(); if (G.mode === 'comp' && G.round > 0 && G.set.battleSize === 'auto' && G.perf.pending) resizeRoster(G.perf.pending); G.round++; G.state = G.mode === 'comp' ? 'freeze' : 'live'; clearCombatFeedback(); G.timer = G.mode === 'dm' ? DM_TIME : G.mode === 'range' ? 1e6 : FREEZE; smokeClear(); G.flashT = 0; PROG.resetRound(); G.huntAll = false; G.timescale = 1; for (const n of G.nades) scene.remove(n.m); G.nades = [];
  for (const e of G.ents) { e.alive = false; } for (const e of G.ents) spawnEnt(e); bombReset(); if (G.mode === 'range') TRAIN.reset(false); else TRAIN.active = false;
  if (G.mode === 'comp') { const me = BOMB.carrier === G.player, atk = G.team === 'red'; banner(`第 ${G.round} 回合`, me ? '你携带墨核 · 送到 A / B 点按住 E 安放' : atk ? '进攻方 · 掩护队友安放墨核' : '防守方 · 守住 A / B 点,墨核被安放后去拆除'); }
  else if (G.mode === 'range') { const pl = G.player; for (const k of ['ak', 'deagle']) giveWeapon(pl, k); for (const k of NADES) pl.nades[k] = 1; switchTo('ak'); banner('靶场 · 精度训练', 'T 开始 30 秒训练 · Y 横移靶 · M 训练设置', 'go'); }
  else banner('死斗模式', `率先 ${DM_KILLS} 次击倒的队伍获胜 · 随时可采购换装`); SFX.ui(660);
}
function checkRoundEnd() { const a = { red: 0, blue: 0 }; for (const e of G.ents) if (e.alive) a[e.team]++; if (!a.blue) endRound('red', '防守方全员阵亡'); else if (!a.red && BOMB.state !== 'planted') endRound('blue', '进攻方全员阵亡'); }
function endRound(win, reason) {
  if (G.state !== 'live') return; G.state = 'roundEnd'; G.timer = 5; G.score[win]++; G.timescale = .3; setTimeout(() => G.timescale = 1, 900); const lose = win === 'red' ? 'blue' : 'red'; G.lossStreak[win] = 0; G.lossStreak[lose]++;
  for (const e of G.ents) { e.money = Math.min(16000, e.money + (e.team === win ? 3250 : 1400 + Math.min(4, G.lossStreak[lose]) * 500)); if (e.alive && !e.isPlayer) { e.keep = true; e.weaponKeep = e.weapon; } }
  const mine = win === G.team; const mvp = PROG.mvp(win); banner(mine ? '回合胜利' : '回合失利', `${reason || (win === 'blue' ? '蓝方拿下本回合' : '红方拿下本回合')}${mvp ? ' · ' + mvp : ''}`, mine ? 'win' : 'lose'); SFX.bell(mine); closeBuy(); PROG.report('回合伤害统计');
}
function endMatch(win) { G.state = 'matchEnd'; $('specControls').hidden = true; const mine = win === G.team; $('endTitle').textContent = mine ? '胜 利' : '落 败'; $('endSub').textContent = `${G.score.blue} : ${G.score.red} · 击倒 ${G.player.kills} · 阵亡 ${G.player.deaths}`; $('end').classList.add('on'); $('dead').classList.remove('on'); SFX.bell(mine); if (document.exitPointerLock) document.exitPointerLock(); }
function updateFlow(dt) {
  if (G.state === 'menu' || G.state === 'matchEnd') return; G.timer -= dt;
  if (G.state === 'freeze' && G.timer <= 0) { G.state = 'live'; G.timer = ROUND_TIME; banner('行动开始', '', 'go'); SFX.ui(990); }
  else if (G.state === 'live') { if (G.mode === 'comp') { if (G.timer <= 0 && BOMB.state !== 'planted') endRound('blue', '时间耗尽'); }
    else if (G.mode === 'range') { const pl = G.player; if (!pl.alive) spawnEnt(pl); pl.hp = 100; for (const k in pl.ammo) pl.ammo[k].res = WEAPONS[k].res; for (const e of G.bots) if (!e.alive && G.now >= e.respawnT - 1.2) spawnEnt(e); }
    else { if (G.timer <= 0) endMatch(G.score.red > G.score.blue ? 'red' : 'blue'); for (const e of G.ents) if (!e.alive && G.now >= e.respawnT) spawnEnt(e); } }
  else if (G.state === 'roundEnd' && G.timer <= 0) { if (Math.max(G.score.red, G.score.blue) >= WIN_ROUNDS) endMatch(G.score.red > G.score.blue ? 'red' : 'blue'); else startRound(); }
}

/* ---------------- buy ---------------- */
function canBuy() { const pl = G.player; if (!pl || !pl.alive) return false; if (G.mode !== 'comp') return true; const r = MAP.spawn[pl.team]; const inZone = pl.pos.x > r.x1 - 6 && pl.pos.x < r.x2 + 6 && pl.pos.z > r.z1 - 4 && pl.pos.z < r.z2 + 4; return G.state === 'freeze' || (G.state === 'live' && G.timer > ROUND_TIME - 20 && inZone); }
function toggleBuy() { if (G.buyOpen) return closeBuy(); if (!canBuy()) { banner('无法采购', '仅限准备阶段或开局 20 秒内在出生区', 'lose'); SFX.deny(); return; } G.mapOpen = false; $('tactical').classList.remove('on'); G.buyOpen = true; unlockUI(); drawBuy(); $('buy').classList.add('on'); SFX.ui(); }
function closeBuy() { const was = G.buyOpen; G.buyOpen = false; $('buy').classList.remove('on'); clearInput(); if (was && !G.paused && G.state !== 'menu' && G.state !== 'matchEnd') lock(); }
function drawBuy() { const pl = G.player; $('buyMoney').textContent = '$' + pl.money; const bill = rebuyBill(), loss = 1400 + Math.min(4, G.lossStreak[pl.team] + 1) * 500; $('buyBudget').textContent = G.mode === 'comp' ? `当前 $${pl.money} · 若本局落败，回合补助 $${loss} · 先保枪甲，再选投掷物` : '训练与死斗免费换装'; $('rebuy').disabled = !bill.keys.length || !bill.cost || G.mode === 'comp' && bill.cost > pl.money; $('rebuy').textContent = !bill.keys.length ? '尚无上次配置' : !bill.cost ? '上次配置已齐备' : G.mode === 'comp' ? `复购上次配置 · $${bill.cost}${bill.cost > pl.money ? '（资金不足）' : ''}` : '领取上次配置'; $('buyGrid').innerHTML = BUY_LIST.map((k, i) => { const armor = k === 'armor', w = armor ? { name: '护甲 + 头盔', en: 'PLATE & HELM', price: 1000 } : WEAPONS[k], own = armor ? pl.armor >= 100 && pl.helmet : (WEAPONS[k].nade ? pl.nades[k] > 0 : pl.inv[w.slot] === k), poor = G.mode === 'comp' && pl.money < w.price;
    return `<button type="button" data-k="${k}" class="card ${own ? 'own' : poor ? 'poor' : ''}"><b>${(i + 1) % 10}</b>${armor ? '<div class="ico armor">⛨</div>' : `<img class="ico" alt="" src="${G.icons[k]}">`}<div class="nm">${w.name}</div><div class="en">${w.en}</div><div class="spec">${armor ? '减伤防护 · 100 护甲' : w.nade ? '战术投掷 · 数量 1' : w.melee ? '近身行动' : w.pellets ? `${w.mag} 发 · ${w.pellets} 弹丸 × ${w.dmg} · 近身爆发 / ${w.fallStart}m 后衰减` : `${w.mag} 发 · 基础伤害 ${w.dmg} · ${w.reload.toFixed(1)}s 换弹`}</div><div class="pr">${own ? '已装备' : G.mode !== 'comp' ? '免费领取' : '$' + w.price}</div></button>`; }).join(''); }
function buy(k) { const pl = G.player; if (!canBuy()) return closeBuy(); const armor = k === 'armor', price = armor ? 1000 : WEAPONS[k].price; if (armor ? pl.armor >= 100 && pl.helmet : (WEAPONS[k].nade ? pl.nades[k] > 0 : pl.inv[WEAPONS[k].slot] === k)) return SFX.deny(); if (G.mode === 'comp' && pl.money < price) return SFX.deny();
  if (G.mode === 'comp') pl.money -= price; if (armor) { pl.armor = 100; pl.helmet = true; } else { giveWeapon(pl, k); if (!WEAPONS[k].nade) switchTo(k); } SFX.buy(); if (!G.rebuying) { G.set.lastBuy = [pl.inv[1], pl.inv[2] !== 'p9' ? pl.inv[2] : null, pl.armor > 0 ? 'armor' : null, ...nadeList(pl)].filter(Boolean); localStorage.setItem('inkstrike', JSON.stringify(G.set)); } drawBuy(); return true; }

function itemOwned(k) { const pl = G.player; return k === 'armor' ? pl.armor >= 100 && pl.helmet : WEAPONS[k].nade ? pl.nades[k] > 0 : pl.inv[WEAPONS[k].slot] === k; }
function rebuyBill() { const keys = Array.isArray(G.set.lastBuy) ? [...new Set(G.set.lastBuy)].filter(k => BUY_LIST.includes(k)) : [], missing = G.player ? keys.filter(k => !itemOwned(k)) : []; return { keys, missing, cost: missing.reduce((n, k) => n + (k === 'armor' ? 1000 : WEAPONS[k].price), 0) }; }
function rebuy() { if (!canBuy()) return; const b = rebuyBill(), pl = G.player; if (!b.cost || G.mode === 'comp' && b.cost > pl.money) return SFX.deny(); const before = pl.money; G.rebuying = true; try { for (const k of b.missing) buy(k); } finally { G.rebuying = false; } combatNotice('配置已补齐', G.mode === 'comp' ? `实付 $${before - pl.money} · 余 $${pl.money}` : '免费领取'); drawBuy(); }

/* ---------------- HUD ---------------- */
function clearCombatFeedback() { G.hitT = 0; G.hitKill = false; G.splats = []; G.dmgDirs = []; G.shake = 0; G.flashT = 0; G.labelT = -9; G.allyLabels = []; FX.nums = []; if ($('combatNotice')) $('combatNotice').classList.remove('on'); }
function combatNotice(t, s = '') { $('combatNotice').textContent = t + (s ? ' · ' + s : ''); $('combatNotice').classList.add('on'); G.noticeUntil = G.now + 2.1; }
function passCoreFeedback() { if (passCore()) combatNotice('已交接墨核', BOMB.carrier.name); else combatNotice('暂不能交接', '携核时靠近 5 米内可见的队友'); }
function precisionState(pl, w) { if (w.nade || w.melee) return { text: '', value: 1 }; const base = w.spread + (w.scope && !pl.scoped ? w.noScope : 0), value = clamp(1 - Math.max(0, (pl.spread || 0) - base) / Math.max(.018, w.moveSp), 0, 1); return { value, text: !pl.onGround ? '空中 · 散布扩大' : Math.hypot(pl.vel.x, pl.vel.z) > 1.8 ? '移动中 · 急停再射' : pl.shots > 2 ? '连射恢复中' : pl.crouchAmt > .5 ? '蹲姿 · 精度提升' : '稳态 · 精度就绪' }; }
function banner(t, s, cls) { const b = $('banner'); b.className = 'on ' + (cls ? 'b-' + cls : ''); $('bannerT').textContent = t; $('bannerS').textContent = s || ''; clearTimeout(G._bt); G._bt = setTimeout(() => b.className = '', 2300); }
function addFeed(by, e, wkey, head) { G.feed.push({ t: G.now, html: `<span class="${by ? by.team : ''}">${by && by !== e ? by.name : ''}</span> <i>${WEAPONS[wkey] ? WEAPONS[wkey].name.split(' ')[0] : '坠落'}${head ? ' ◎' : ''}</i> <span class="${e.team}">${e.name}</span>`, me: (by && by.isPlayer) || e.isPlayer }); if (G.feed.length > 5) G.feed.shift(); drawFeed(); }
function drawFeed() { $('feed').innerHTML = G.feed.map(f => `<div class="${f.me ? 'me' : ''}">${f.html}</div>`).join(''); }
function drawBoard() { const row = e => `<tr class="${e.isPlayer ? 'me' : ''} ${e.alive ? '' : 'out'}"><td>${e.name}${e.mvps ? ' ★' + e.mvps : ''}${BOMB.carrier === e && e.team === G.team ? ' ◆' : ''}</td><td>${e.kills}</td><td>${e.deaths}</td><td>${G.mode === 'comp' && e.team === G.team ? '$' + e.money : ''}</td></tr>`;
  $('boardIn').innerHTML = ['blue', 'red'].map(t => `<table class="${t}"><caption>${t === 'blue' ? '蓝方 · 靛青' : '红方 · 朱砂'}　${G.score[t]}</caption><tr><th>代号</th><th>击倒</th><th>阵亡</th><th>资金</th></tr>${G.ents.filter(e => e.team === t).sort((a, b) => b.kills - a.kills).map(row).join('')}</table>`).join(''); }
let _hudT = 0;
function updateHUD(dt) {
  const pl = G.player; _hudT -= dt; if (_hudT <= 0) { _hudT = .1; const a = pl.ammo[pl.cur], w = WEAPONS[pl.cur], al = { red: 0, blue: 0 }; for (const e of G.ents) if (e.alive) al[e.team]++;
    $('hp').textContent = Math.max(0, Math.ceil(pl.hp)); $('hpBar').style.width = clamp(pl.hp, 0, 100) + '%'; $('hpBox').classList.toggle('low', pl.hp <= 30); $('ar').textContent = Math.ceil(pl.armor); $('arBar').style.width = pl.armor + '%';
    $('mag').textContent = a ? a.mag : (w.nade ? pl.nades[pl.cur] : '—'); $('res').textContent = a ? a.res : ''; $('wname').textContent = w.name; $('wen').textContent = w.en; $('money').textContent = G.mode === 'comp' ? '$' + pl.money : '';
    const planted = BOMB.state === 'planted' && G.state === 'live', t = Math.max(0, Math.ceil(planted ? BOMB.t : G.timer)); $('timer').textContent = G.mode === 'range' ? '∞' : `${planted ? '◆ ' : ''}${(t / 60) | 0}:${String(t % 60).padStart(2, '0')}`; $('timer').classList.toggle('warn', G.state === 'live' && (t <= 10 || planted));
    $('obj').textContent = G.mode !== 'comp' ? '' : BOMB.carrier === pl ? (canPlant(pl) ? (TOUCH.on ? '◆ 按住「互动」安放墨核' : '◆ 按住 E 安放墨核') : '◆ 你携带墨核 → A / B') : canDefuse(pl) ? (TOUCH.on ? '按住「互动」拆除墨核' : '按住 E 拆除墨核') : planted ? `墨核已安放于 ${SITES[BOMB.site].name}` : BOMB.state === 'dropped' ? '墨核掉落在地' : ''; $('sB').textContent = G.score.blue; $('sR').textContent = G.score.red;
    $('aB').textContent = G.mode === 'comp' ? `${al.blue} / ${G.teamSize} 存活` : ''; $('aR').textContent = G.mode === 'comp' ? `${al.red} / ${G.teamSize} 存活` : ''; $('zone').textContent = MAP.zoneAt(pl.pos.x, pl.pos.z); $('phase').textContent = G.state === 'freeze' ? '准备' : G.mode === 'dm' ? `死斗 · ${G.teamSize}v${G.teamSize}` : G.mode === 'range' ? '靶场' : `R${G.round} · ${G.teamSize}v${G.teamSize}`;
    if (G.now > (G.labelT || -9)) { G.labelT = G.now + .18; G.allyLabels = G.ents.filter(e => e !== pl && e.alive && e.team === pl.team && e.pos.distanceTo(pl.pos) < 38 && botSee(pl, e)); } $('training').hidden = G.mode !== 'range'; $('training').textContent = TRAIN.label(); $('orderState').textContent = G.order && G.order.until > G.now ? `${G.order.kind === 'rally' ? '集合' : G.order.kind + ' 点'} · 小队响应中` : ''; if (G.now > (G.noticeUntil || 0)) $('combatNotice').classList.remove('on');
    $('slots').innerHTML = [[1, pl.inv[1]], [2, pl.inv[2]], [3, 'knife'], ...nadeList(pl).map(k => [4, k])].map(([n, k]) => k ? `<span class="${k === pl.cur ? 'cur' : ''}">${n} ${WEAPONS[k].name.split(' ')[0]}</span>` : '').join('');
    const now = G.now; if (G.feed.length && now - G.feed[0].t > 6) { G.feed.shift(); drawFeed(); } $('scope').classList.toggle('on', !!(w.scope && pl.scoped && pl.alive)); $('optic').className = w.optic && pl.scoped && pl.alive ? 'on ' + w.optic : ''; $('specControls').hidden = pl.alive || G.mode !== 'comp'; $('specLabel').textContent = G.spec && G.spec.alive ? G.spec.name + ' · ' + Math.ceil(G.spec.hp) + ' HP' : '等待存活队友'; if (G.buyOpen) $('buyMoney').textContent = '$' + pl.money; }
  $('captureMouse').hidden = TOUCH.on || G.noLock || !!document.pointerLockElement || !pl.alive || G.paused || G.buyOpen || G.mapOpen || !['live', 'freeze'].includes(G.state); const act = pl.act; $('prog').style.display = act ? 'block' : 'none'; if (act) { $('progBar').style.width = clamp(act.t / (act.type === 'plant' ? PLANT_T : DEFUSE_T) * 100, 0, 100) + '%'; $('progLab').textContent = act.type === 'plant' ? '安放中…' : '拆除中…'; }
  if (G.flashT > 0) G.flashT -= dt; $('flashOv').style.opacity = clamp((G.flashT || 0) / .9, 0, 1); $('smokeOv').style.opacity = pl.alive ? inSmoke(camera.position) * .93 : 0;
  const w = WEAPONS[pl.cur], a = pl.ammo[pl.cur], precision = precisionState(pl, w); $('precisionBar').style.width = Math.round(precision.value * 100) + '%'; $('weaponState').textContent = G.now < (pl.spawnProtectedUntil || 0) ? '出生保护 · 开火立即解除' : pl.reloadEnd >= 0 ? `换弹中 ${Math.ceil((pl.reloadEnd - G.now) * 10) / 10}s` : a && a.mag <= Math.ceil(w.mag * .2) ? (TOUCH.on ? '余弹不足 · 点换弹' : '余弹不足 · R 换弹') : G.noLock && !TOUCH.on && G.set.aimMode === 'trackpad' && pl.alive ? 'H 按住复位光标 · Z 开火 · V 瞄准' : ''; $('moveState').textContent = pl.alive ? precision.text : ''; if (G.mapOpen) drawTactical(); drawFx(dt); drawRadar();
}
function drawFx(dt) {
  const g = fxg, R = G.fxDpr || 1, W = fxc.width / R, H = fxc.height / R, pl = G.player, cx = W / 2, cy = H / 2; g.setTransform(1, 0, 0, 1, 0, 0); g.clearRect(0, 0, fxc.width, fxc.height); g.setTransform(R, 0, 0, R, 0, 0);   // HUD overlay at device resolution (names stay sharp on phones)
  for (let i = G.splats.length - 1; i >= 0; i--) { const s = G.splats[i]; s.t -= dt; if (s.t <= 0) { G.splats.splice(i, 1); continue; } g.globalAlpha = Math.min(1, s.t) * .8 * G.set.inkFx; g.fillStyle = '#d42a2a'; const ex = s.x < .5 ? s.x * .3 : 1 - (1 - s.x) * .3, ey = s.y; g.save(); g.translate(ex * W, ey * H); g.rotate(s.r); g.beginPath(); for (let k = 0; k <= 18; k++) { const a = k / 18 * 6.2832, r = s.s * (.6 + .4 * Math.sin(k * 2.7 + s.r * 5) + (k % 3 === 0 ? .5 : 0)); k ? g.lineTo(Math.cos(a) * r, Math.sin(a) * r) : g.moveTo(Math.cos(a) * r, Math.sin(a) * r); } g.fill(); g.restore(); }
  g.globalAlpha = 1; if (pl.alive && pl.hp <= 30) { const gr = g.createRadialGradient(cx, cy, H * .35, cx, cy, H * .8); gr.addColorStop(0, 'rgba(212,42,42,0)'); gr.addColorStop(1, `rgba(212,42,42,${(.25 + .1 * Math.sin(G.now * 5)) * G.set.inkFx})`); g.fillStyle = gr; g.fillRect(0, 0, W, H); }
  for (let i = G.dmgDirs.length - 1; i >= 0; i--) { const d = G.dmgDirs[i]; d.t -= dt; if (d.t <= 0) { G.dmgDirs.splice(i, 1); continue; } const a = angDiff(Math.atan2(-(d.x - pl.pos.x), -(d.z - pl.pos.z)), pl.yaw); g.save(); g.translate(cx, cy); g.rotate(-a); g.globalAlpha = Math.min(1, d.t); g.strokeStyle = '#d42a2a'; g.lineWidth = 7; g.beginPath(); g.arc(0, 0, 120, -Math.PI / 2 - .32, -Math.PI / 2 + .32); g.stroke(); g.restore(); }
  g.globalAlpha = 1; g.font = 'bold 17px "IBM Plex Mono", monospace'; g.textAlign = 'center';
  for (const q of FX.nums) { _cv.set(q.x, q.y, q.z).applyMatrix4(camera.matrixWorldInverse); if (_cv.z > -.3) continue; _cv.set(q.x, q.y, q.z).project(camera); g.globalAlpha = 1 - q.t / .9; g.fillStyle = q.head ? '#d42a2a' : '#16161c'; g.fillText((q.head ? '◎ ' : '') + q.val, (_cv.x * .5 + .5) * W, (-_cv.y * .5 + .5) * H); }
  g.font = '600 12px "IBM Plex Mono", monospace'; for (const e of G.allyLabels || []) { if (!e.alive) continue; _cv.set(e.pos.x, e.pos.y + 2.05, e.pos.z).applyMatrix4(camera.matrixWorldInverse); if (_cv.z > -.5) continue; _cv.set(e.pos.x, e.pos.y + 2.05, e.pos.z).project(camera); if (Math.abs(_cv.x) > 1.1 || Math.abs(_cv.y) > 1.1) continue; const sx = Math.round((_cv.x * .5 + .5) * W), sy = Math.round((-_cv.y * .5 + .5) * H), col = pl.team === 'red' ? '#d42a2a' : '#2d6cb3', tw = Math.round(g.measureText(e.name).width) + 12; g.globalAlpha = 1; g.fillStyle = '#f5f2ea'; g.fillRect(sx - tw / 2, sy - 9, tw, 17); g.fillStyle = col; g.fillRect(sx - tw / 2, sy + 7, tw, 2); g.fillText(e.name, sx, sy + 4); }
  g.globalAlpha = 1; if (!pl.alive || G.state === 'menu') return;
  if (!pl.scoped && !WEAPONS[pl.cur].scope) { const XC = { ink: '#16161c', red: '#d42a2a', blue: '#2d6cb3', amber: '#e9a520', green: '#2e9e4a' }[G.set.xh] || '#16161c', sz = G.set.xhSize, gap = (G.set.xhStatic ? 5 : 4 + (pl.spread || 0) * 900) * sz, L = 8 * sz; g.lineCap = 'butt'; for (const [c, lw] of [['#f5f2ea', 5 * sz], [XC, 2.4 * sz]]) { g.strokeStyle = c; g.lineWidth = lw; g.beginPath(); g.moveTo(cx - gap - L, cy); g.lineTo(cx - gap, cy); g.moveTo(cx + gap, cy); g.lineTo(cx + gap + L, cy); g.moveTo(cx, cy - gap - L); g.lineTo(cx, cy - gap); g.moveTo(cx, cy + gap); g.lineTo(cx, cy + gap + L); g.stroke(); } g.fillStyle = '#f5f2ea'; g.fillRect(cx - 2, cy - 2, 4, 4); g.fillStyle = XC; g.fillRect(cx - 1, cy - 1, 2, 2); }
  if (G.hitT > 0) { G.hitT -= dt; const k = G.hitT / .22, r0 = 7 + (1 - k) * 5, r1 = r0 + (G.hitKill ? 11 : 7); g.strokeStyle = G.hitKill ? '#d42a2a' : '#16161c'; g.lineWidth = G.hitKill ? 3 : 2; g.globalAlpha = k; g.beginPath(); for (const [sx, sy] of [[1, 1], [1, -1], [-1, 1], [-1, -1]]) { g.moveTo(cx + sx * r0, cy + sy * r0); g.lineTo(cx + sx * r1, cy + sy * r1); } g.stroke(); g.globalAlpha = 1; }
}
function drawRadar() {
  const g = rg, S = 176, pl = G.player, k = 2.3, ref = pl.alive ? pl : (G.spec || pl); g.clearRect(0, 0, S, S); g.save(); g.beginPath(); g.arc(S / 2, S / 2, S / 2 - 2, 0, 6.2832); g.clip(); g.fillStyle = '#f5f2ea'; g.fillRect(0, 0, S, S);
  g.translate(S / 2, S / 2); g.rotate(ref.yaw); g.scale(k / 4, k / 4); g.drawImage(MAP.mini, -(ref.pos.x + 64) * 4, -(ref.pos.z + 56) * 4); g.scale(4 / k, 4 / k);
  for (const e of G.ents) { if (!e.alive || e === ref) continue; const mine = e.team === pl.team; if (!mine) continue; const ep = e.pos; g.fillStyle = mine ? '#2d6cb3' : '#d42a2a'; if (pl.team === 'red') g.fillStyle = mine ? '#d42a2a' : '#2d6cb3'; g.beginPath(); g.arc((ep.x - ref.pos.x) * k, (ep.z - ref.pos.z) * k, 3.6, 0, 6.2832); g.fill(); }
  if (G.mode === 'comp' && (BOMB.state === 'planted' || (BOMB.state === 'dropped' && pl.team === 'red'))) { const bx = (BOMB.pos.x - ref.pos.x) * k, bz = (BOMB.pos.z - ref.pos.z) * k; g.fillStyle = '#e9a520'; g.strokeStyle = '#16161c'; g.lineWidth = 1.5; g.beginPath(); g.moveTo(bx, bz - 6); g.lineTo(bx + 6, bz); g.lineTo(bx, bz + 6); g.lineTo(bx - 6, bz); g.closePath(); g.fill(); g.stroke(); }
  g.restore(); g.fillStyle = '#16161c'; g.beginPath(); g.moveTo(S / 2, S / 2 - 7); g.lineTo(S / 2 + 5, S / 2 + 5); g.lineTo(S / 2, S / 2 + 2); g.lineTo(S / 2 - 5, S / 2 + 5); g.fill(); g.strokeStyle = '#16161c'; g.lineWidth = 2; g.beginPath(); g.arc(S / 2, S / 2, S / 2 - 2, 0, 6.2832); g.stroke();
}

/* ---------------- UI wiring ---------------- */
function bindUI() {
  const seg = (id, key, cast) => $(id).querySelectorAll('button').forEach(b => { b.classList.toggle('sel', String(G[key]) === b.dataset.v); b.onclick = () => { $(id).querySelectorAll('button').forEach(x => x.classList.remove('sel')); b.classList.add('sel'); G[key] = cast(b.dataset.v); SFX.init(); SFX.ui(); }; });
  seg('optMode', 'mode', String); seg('optDiff', 'diff', Number); seg('optTeam', 'team', String); for (const id of ['optMode', 'optTeam']) $(id).addEventListener('click', updateBrief); $('buyGrid').addEventListener('click', e => { const c = e.target.closest('.card'); if (c) buy(c.dataset.k); }); $('buyClose').onclick = closeBuy; $('mapPreview').onclick = () => toggleMap(true); $('mapClose').onclick = () => toggleMap(false); $('sQuality').value = G.set.quality; $('sQuality').onchange = () => { G.set.quality = $('sQuality').value; localStorage.setItem('inkstrike', JSON.stringify(G.set)); applyQuality(); }; $('optSize').querySelectorAll('button').forEach(b => { b.classList.toggle('sel', b.dataset.v === String(G.set.battleSize)); b.onclick = () => { G.set.battleSize = b.dataset.v; $('optSize').querySelectorAll('button').forEach(q => q.classList.toggle('sel', q === b)); localStorage.setItem('inkstrike', JSON.stringify(G.set)); updateBrief(); }; });
  $('captureMouse').onclick = () => { clearInput(); lock(); }; $('specPrev').onclick = () => cycleSpectator(-1); $('specNext').onclick = () => cycleSpectator(1); $('looksBtn').onclick = () => { updateActorPreview(); $('looks').classList.add('on'); }; $('looksClose').onclick = () => $('looks').classList.remove('on'); $('sActorStyle').onchange = () => { setActorStyle($('sActorStyle').value); updateActorPreview(); }; $('sMap').value = MAP.id; $('sMap').onchange = () => { G.set.map = $('sMap').value; localStorage.setItem('inkstrike', JSON.stringify(G.set)); const url = new URL(location.href); url.searchParams.delete('map'); url.searchParams.set('mode', G.mode); url.searchParams.set('team', G.team); url.searchParams.set('diff', G.diff); location.href = url.href; }; $('sAimMode').value = G.set.aimMode; $('sAimMode').onchange = () => { G.set.aimMode = $('sAimMode').value; localStorage.setItem('inkstrike', JSON.stringify(G.set)); resetLook(); };
  $('rebuy').onclick = rebuy; $('corePass').onclick = passCoreFeedback; document.querySelectorAll('[data-order]').forEach(b => b.onclick = () => { if (issueOrder(b.dataset.order)) { combatNotice(b.dataset.order === 'auto' ? '恢复自主战术' : '小队指令已发送'); drawTactical(); } else combatNotice('当前无法指挥', '进入竞技模式后向己方小队下令'); }); $('trainStart').onclick = () => { TRAIN.reset(true); toggleMap(false); }; $('trainMotion').onclick = () => TRAIN.setMoving(!TRAIN.moving);
  $('start').onclick = () => startMatch(); $('resume').onclick = () => setPause(false); $('quit').onclick = $('again').onclick = () => { G.state = 'menu'; G.paused = false; if (G.rangeTeam) { G.team = G.rangeTeam; G.rangeTeam = null; } for (const id of ['pause', 'end', 'hud', 'dead', 'buy', 'report', 'tactical', 'scope', 'optic', 'board', 'looks']) $(id).classList.remove('on'); $('menu').classList.add('on'); $('menu').scrollTop = 0; G.buyOpen = G.mapOpen = false; $('specControls').hidden = $('captureMouse').hidden = true; PROG.resetStreak(); clearCombatFeedback(); unlockUI(); updateBrief(); };
  $('sXh').querySelectorAll('button').forEach(b => { b.classList.toggle('sel', b.dataset.v === G.set.xh); b.onclick = () => { G.set.xh = b.dataset.v; $('sXh').querySelectorAll('button').forEach(x => x.classList.toggle('sel', x === b)); localStorage.setItem('inkstrike', JSON.stringify(G.set)); }; });
  const xs = $('sXhStatic'); xs.checked = !!G.set.xhStatic; xs.onchange = () => { G.set.xhStatic = xs.checked ? 1 : 0; localStorage.setItem('inkstrike', JSON.stringify(G.set)); };
  for (const [id, key, fn] of [['sSens', 'sens', v => v], ['sFov', 'fov', v => v], ['sVol', 'vol', v => { SFX.setVol(v); return v; }], ['sXhSize', 'xhSize', v => v], ['sMotion', 'motion', v => v], ['sInkFx', 'inkFx', v => v]]) { const el = $(id), lab = $(id + 'V'); el.value = G.set[key]; lab.textContent = G.set[key]; el.oninput = () => { G.set[key] = fn(+el.value); lab.textContent = el.value; localStorage.setItem('inkstrike', JSON.stringify(G.set)); }; }
}

/* ---------------- camera + frame ---------------- */
function updateCamera(dt) {
  const pl = G.player; let fov = G.set.fov; G.shake = damp(G.shake, 0, 9, dt);
  if (pl.alive) { G.spec = null; camera.position.set(pl.pos.x, pl.pos.y + eyeY(pl) + pl.stepSmooth, pl.pos.z); const motion = G.set.motion, sh = G.shake * .012 * motion; camera.rotation.set(pl.pitch + pl.recP + pl.punch * .5 * motion + gauss() * sh, pl.yaw + pl.recY + gauss() * sh, (pl.roll + pl.punch * .3) * motion); if (pl.scoped) { const w = WEAPONS[pl.cur]; fov = w.scope ? (pl.scoped === 1 ? 46 : 26) : Math.min(G.set.fov * .84, w.adsFov || 66); } }
  else if (G.deathCam) { const d = G.deathCam; d.t += dt; if (d.t < 2.6 || G.mode === 'dm') { const h = Math.min(3.2, .4 + d.t * 1.6), bx = pl.pos.x + Math.sin(d.yaw) * h * .8, bz = pl.pos.z + Math.cos(d.yaw) * h * .8; camera.position.set(bx, pl.pos.y + h, bz); camera.lookAt(pl.pos.x, pl.pos.y + .3, pl.pos.z); }
    else { if (!G.spec || !G.spec.alive) cycleSpectator(1);
      if (G.spec) { const s = G.spec, bx = s.pos.x + Math.sin(s.yaw) * 2.6, bz = s.pos.z + Math.cos(s.yaw) * 2.6; _cv.set(bx, s.pos.y + 2.1, bz); const ok = segClear(s.pos.x, s.pos.y + 1.6, s.pos.z, bx, s.pos.y + 2.1, bz); if (!ok) _cv.set(s.pos.x, s.pos.y + 2.3, s.pos.z); camera.position.lerp(_cv, 1 - Math.exp(-8 * dt)); camera.rotation.set(damp(camera.rotation.x, s.pitch - .18, 8, dt), camera.rotation.y + angDiff(s.yaw, camera.rotation.y) * (1 - Math.exp(-8 * dt)), 0); } } }
  if (Math.abs(camera.fov - fov) > .05) { camera.fov = damp(camera.fov, fov, 22, dt); camera.updateProjectionMatrix(); }
  SFX.L.x = camera.position.x; SFX.L.z = camera.position.z; SFX.L.yaw = camera.rotation.y;
}
function frame(dt) {
  if (G.state === 'menu') { if (camera.fov !== G.set.fov) { camera.fov = G.set.fov; camera.updateProjectionMatrix(); } const t = G.now * .04; const m = MAP.menuCamera; camera.position.set(m.pos[0] + Math.sin(t) * 2, m.pos[1], m.pos[2]); camera.lookAt(...m.target); renderer.clear(); renderer.render(scene, camera); return; }
  if (!G.paused && G.state !== 'matchEnd') { const sdt = dt * G.timescale; G.now += sdt; updateFlow(sdt); const pl = G.player;
    if (G.state !== 'matchEnd' && G.state !== 'menu') { if (TOUCH.on) updateTouch(sdt); if (pl.alive) updatePlayer(sdt); TRAIN.update(sdt); for (const b of G.bots) updateBot(b, sdt, G.now); updateNades(sdt); bombUpdate(sdt); smokeUpdate(sdt); FX.update(sdt, camera); updateCamera(sdt); VM.update(sdt, pl, WEAPONS[pl.cur], G.mdx, G.mdy); updateHUD(dt);
      if (G.now - (G._spotT || 0) > .2) { G._spotT = G.now; if (pl.alive) for (const e of G.ents) if (e.alive && e.team !== pl.team && botSee(pl, e)) { const a = Math.abs(angDiff(Math.atan2(-(e.pos.x - pl.pos.x), -(e.pos.z - pl.pos.z)), pl.yaw)); if (a < 1 && !(G.flashT > .15)) markSpotted(e, pl.team, G.now); } } }
    G.mdx = G.mdy = 0; G.fireEdge = G.altEdge = false; }
  renderer.clear(); renderer.render(scene, camera); if (G.player && G.player.alive) { renderer.clearDepth(); renderer.render(VM.scene, VM.cam); }
}

/* ---------------- field map + adaptive roster ---------------- */
function addRosterBot(team, money) { const n = G.botSerial++, name = BOT_NAMES[n % BOT_NAMES.length] + (n >= BOT_NAMES.length ? ' ' + (1 + Math.floor(n / BOT_NAMES.length)) : ''), b = makeBot(team, name, scene); b.money = money; G.ents.push(b); G.bots.push(b); return b; }
function resizeRoster(size) { for (const team of ['blue', 'red']) { const want = size - (team === G.team ? 1 : 0), list = G.bots.filter(b => b.team === team), cash = Math.round(list.reduce((n, b) => n + b.money, 0) / Math.max(1, list.length)); while (list.length > want) { const b = list.pop(); scene.remove(b.model.root); G.ents.splice(G.ents.indexOf(b), 1); G.bots.splice(G.bots.indexOf(b), 1); disposeBotModel(b); } while (list.length < want) list.push(addRosterBot(team, Math.max(800, cash))); } G.teamSize = size; G.set.autoTeamSize = size; G.perf.pending = null; G.perf.samples = []; G.perf.cpu = []; G.perf.elapsed = 0; localStorage.setItem('inkstrike', JSON.stringify(G.set)); }
function samplePerformance(elapsed, cpu) { if (G.manualStep || G.state !== 'live' || G.paused || G.buyOpen || G.mapOpen || document.hidden || G.mode === 'range' || elapsed < 1) return; const p = G.perf; p.samples.push(Math.min(1000, elapsed)); p.cpu.push(cpu); p.elapsed += elapsed; if (p.samples.length < 300 && (p.elapsed < 8000 || p.samples.length < 30)) return; const sorted = p.samples.slice().sort((a, b) => a - b), costs = p.cpu.slice().sort((a, b) => a - b); p.p90 = sorted[Math.floor(sorted.length * .9)]; p.ms = costs[Math.floor(costs.length * .9)]; p.samples = []; p.cpu = []; p.elapsed = 0; if (G.set.battleSize !== 'auto') return; const steps = [5, 8, 12], i = steps.indexOf(G.teamSize), next = p.p90 > 28 || p.ms > 20 ? steps[Math.max(0, i - 1)] : p.p90 < 19 && p.ms < 10 ? steps[Math.min(2, i + 1)] : G.teamSize; p.pending = next === G.teamSize ? null : next; G.set.autoTeamSize = next; localStorage.setItem('inkstrike', JSON.stringify(G.set)); }
function updateBrief() { const mode = G.mode, count = G.set.battleSize === 'auto' ? '自动人数' : `${G.set.battleSize}v${G.set.battleSize}`; $('briefTitle').textContent = mode === 'range' ? '靶场 / 每一笔，都可控' : mode === 'dm' ? `死斗 / ${count}` : `竞技 / ${count}`; $('briefText').textContent = mode === 'range' ? '五档距离假人，固定弹道墙。免费取枪，找到属于你的压枪节奏。' : mode === 'dm' ? '无限重生，随时换装。率先拿下 40 次击倒的队伍获胜。' : G.team === 'red' ? '掩护墨核携带者，前往 A 或 B。按住互动键 3.2 秒完成安放。' : '守住两个点位，听声转点。墨核安放后，按住互动键 6 秒拆除。'; $('sizeHint').textContent = G.set.battleSize === 'auto' ? '按实战帧耗时调整 · 竞技在下一回合生效' : '手动固定人数 · 若帧率下降可选择自动'; $('optSize').parentElement.style.display = mode === 'range' ? 'none' : ''; if (MAP.mini) $('briefMap').src = MAP.mini.toDataURL(); $('fieldName').textContent = MAP.name; $('fieldEn').textContent = MAP.en; $('briefMap').alt = MAP.name + '地图概览'; $('mapTitle').textContent = MAP.name + ' / 战术地图'; $('mapNotes').textContent = MAP_CATALOG[MAP.id].description; $('sMap').value = MAP.id; }
function toggleMap(force) { const on = force === undefined ? !G.mapOpen : force; if (on && G.paused) return; G.mapOpen = on; $('rangeControls').hidden = G.mode !== 'range' || G.state !== 'live'; $('squadControls').hidden = G.mode !== 'comp' || G.state === 'menu'; $('tactical').classList.toggle('on', on); if (on) { G.buyOpen = false; $('buy').classList.remove('on'); unlockUI(); drawTactical(); } else { clearInput(); if (G.state !== 'menu' && !G.paused) lock(); } }
function drawTactical() { const c = $('tacticalMap'), g = c.getContext('2d'), sx = c.width / 128, sz = c.height / 112, point = (x, z) => [(x + 64) * sx, (z + 56) * sz]; g.clearRect(0, 0, c.width, c.height); g.drawImage(MAP.mini, 0, 0, c.width, c.height); g.font = 'bold 17px monospace'; g.textAlign = 'center'; for (const [label, x, z, col] of [['蓝方', (MAP.spawn.blue.x1 + MAP.spawn.blue.x2) / 2, (MAP.spawn.blue.z1 + MAP.spawn.blue.z2) / 2, '#2d6cb3'], ['红方', (MAP.spawn.red.x1 + MAP.spawn.red.x2) / 2, (MAP.spawn.red.z1 + MAP.spawn.red.z2) / 2, '#d42a2a']]) { const [px, py] = point(x, z); g.fillStyle = col; g.fillRect(px - 23, py - 14, 46, 28); g.fillStyle = label.length === 1 ? '#16161c' : '#f5f2ea'; g.fillText(label, px, py + 6); } if (G.state === 'menu') return; for (const e of G.ents) { const mine = e.team === G.team; if (!e.alive || !mine) continue; const ep = e.pos, [x, y] = point(ep.x, ep.z); g.save(); g.translate(x, y); g.rotate(-e.yaw); g.fillStyle = e.team === 'blue' ? '#2d6cb3' : '#d42a2a'; g.strokeStyle = '#f5f2ea'; g.lineWidth = 2; g.beginPath(); if (e.isPlayer) { g.moveTo(0, -9); g.lineTo(7, 7); g.lineTo(0, 3); g.lineTo(-7, 7); g.closePath(); } else g.arc(0, 0, 5, 0, Math.PI * 2); g.fill(); g.stroke(); g.restore(); } if (G.mode === 'comp' && (BOMB.state === 'planted' || BOMB.state === 'dropped' && G.team === 'red')) { const [x, y] = point(BOMB.pos.x, BOMB.pos.z); g.fillStyle = '#e9a520'; g.fillRect(x - 5, y - 5, 10, 10); } }
window.render_game_to_text = () => JSON.stringify({ coordinates: 'meters; x east, y up, z south; north is -z', state: G.state, mode: G.mode, teamSize: G.teamSize, paused: G.paused, buyOpen: G.buyOpen, mapOpen: G.mapOpen, score: G.score, round: G.round, player: G.player && { position: G.player.pos, alive: G.player.alive, hp: G.player.hp, weapon: G.player.cur, ammo: G.player.ammo[G.player.cur], yaw: G.player.yaw, pitch: G.player.pitch }, bots: G.bots.length, objective: { state: BOMB.state, site: BOMB.site, seconds: BOMB.t }, training: G.mode === 'range' ? TRAIN.snapshot() : null, order: G.order || null, spawnProtection: G.player ? Math.max(0, (G.player.spawnProtectedUntil || 0) - G.now) : 0, performance: { p90: G.perf.p90, cpuP90: G.perf.ms, nextTeamSize: G.perf.pending } });
window.advanceTime = ms => { G.manualStep = true; for (let i = 0, n = Math.max(1, Math.round(ms / (1000 / 60))); i < n; i++) frame(1 / 60); };
addEventListener('blur', () => { if (TOUCH.on && TOUCH.edit) return; clearInput(); if (G.state !== 'menu' && G.state !== 'matchEnd') setPause(true); });
document.addEventListener('visibilitychange', () => { if (TOUCH.on && TOUCH.edit) return; if (document.hidden && G.state !== 'menu' && G.state !== 'matchEnd') setPause(true); });

/* Device-calibrated input; no inertial tail or global screen-space delta in unlocked mode. */
const LOOK = { x: null, y: null, native: false, skip: 0 };
function resetLook() { LOOK.x = LOOK.y = null; LOOK.skip = 1; }
function mouseLook(e) { const pl = G.player; if (TOUCH.on || !locked() || !pl || !pl.alive || G.keys.KeyH || (e.target.closest && e.target.closest('button,input,select,.ov'))) { LOOK.x = LOOK.y = null; return; } const native = document.pointerLockElement === renderer.domElement; let dx, dy; if (native !== LOOK.native) { LOOK.native = native; resetLook(); } if (native) { dx = e.movementX; dy = e.movementY; if (LOOK.skip) { LOOK.skip--; return; } } else { const x = e.clientX, y = e.clientY; if (LOOK.x === null) { LOOK.x = x; LOOK.y = y; return; } dx = x - LOOK.x; dy = y - LOOK.y; LOOK.x = x; LOOK.y = y; } if (!Number.isFinite(dx) || !Number.isFinite(dy)) return; const d = Math.hypot(dx, dy), pad = G.set.aimMode === 'trackpad'; if (d > (pad ? 180 : 500)) return; const cap = pad ? 65 : 180, f = d > cap ? cap / d : 1, k = (pad ? .00105 : .0021) * G.set.sens * (camera.fov / G.set.fov); dx *= f; dy *= f; pl.yaw -= dx * k; pl.pitch = clamp(pl.pitch - dy * k, -1.54, 1.54); G.mdx += dx; G.mdy += dy; }
function cycleSpectator(dir = 1) { const pl = G.player; if (!pl || pl.alive || G.mode !== 'comp' || G.state === 'menu') return false; const mates = G.ents.filter(e => e !== pl && e.alive && e.team === pl.team), i = mates.indexOf(G.spec); G.spec = mates.length ? mates[(i < 0 ? (dir < 0 ? mates.length - 1 : 0) : (i + dir + mates.length) % mates.length)] : null; if (G.deathCam) G.deathCam.t = Math.max(2.6, G.deathCam.t); $('deadBy').textContent = G.spec ? `观战中 · ${G.spec.name} · ← / → 或按钮切换` : '暂无存活队友'; $('specLabel').textContent = G.spec ? G.spec.name + ' · ' + Math.ceil(G.spec.hp) + ' HP' : '等待回合结束'; G.fire = G.fireEdge = false; return !!G.spec; }
function updateActorPreview() { if (typeof ACTOR_STYLES === 'undefined') return; const sel = $('sActorStyle'); sel.innerHTML = ACTOR_STYLES.map(q => `<option value="${q.id}">${q.name}</option>`).join(''); const style = ACTOR_STYLES.find(q => q.id === G.set.actorStyle) || ACTOR_STYLES[0]; sel.value = style.id; $('actorDesc').textContent = style.desc + ' · 同步己方小队，轮廓与命中判定不变'; if (G.actorPreviews && G.actorPreviews[style.id]) $('actorPreview').src = G.actorPreviews[style.id]; }
