#!/usr/bin/env node
/* Revision 04 actual UI input + focused regression for player feedback. */
const fs=require('fs'),path=require('path'),http=require('http'),ROOT=path.resolve(__dirname,'..'),out=path.join(ROOT,'outputs/revision-04');
let pw;for(const p of [process.env.PLAYWRIGHT,'playwright','playwright-core','/Users/bing/Developer/codex-tools/npm-global/lib/node_modules/@playwright/cli/node_modules/playwright-core'].filter(Boolean))try{pw=require(p);break}catch(_){}if(!pw)throw Error('Playwright unavailable');
const server=http.createServer((q,r)=>{let f=path.join(ROOT,decodeURIComponent(q.url.split('?')[0]));if(f.endsWith('/'))f+='index.html';if(!f.startsWith(ROOT+path.sep)||!fs.existsSync(f)){r.writeHead(404);return r.end()}r.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(r)}),checks=[],errors=[];let browser;
function yes(v,n,d){if(!v)throw Error(n+' '+JSON.stringify(d||{}));checks.push(n)}
async function frames(p,n){await p.evaluate(n=>{for(let i=0;i<n;i++)frame(1/60)},n)}
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));browser=await pw.chromium.launch({headless:true,args:['--use-angle=metal','--use-gl=angle','--ignore-gpu-blocklist']});const p=await browser.newPage({viewport:{width:1280,height:800}});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{requestAnimationFrame=()=>0;Element.prototype.requestFullscreen=()=>Promise.reject()});await p.goto(`http://127.0.0.1:${server.address().port}/?auto`);await p.waitForFunction(()=>document.getElementById('menu').classList.contains('on'));
for(const id of ['warehouse','dunes','papertown']){await Promise.all([p.waitForNavigation(),p.selectOption('#sMap',id)]);await p.waitForFunction(()=>document.getElementById('menu').classList.contains('on'));yes(await p.evaluate(id=>MAP.id===id&&G.set.map===id&&$('fieldName').textContent===MAP.name,id),'menu changes map and reloads correct world: '+id)}
await p.click('#looksBtn');const images=[];for(const id of ['scribe','scout','warden']){await p.selectOption('#sActorStyle',id);images.push(await p.locator('#actorPreview').getAttribute('src'));yes(await p.evaluate(id=>G.set.actorStyle===id&&$('actorPreview').naturalWidth>0,id),'appearance selection produces real preview: '+id)}yes(new Set(images).size===3,'three equipment presets have distinct rendered previews');await p.click('#looksClose');
await p.click('#optSize [data-v="12"]');await p.click('#start');await p.evaluate(()=>{G.manualStep=true;G.state='live';G.timer=110;G.set.vol=0});
const dots=await p.evaluate(()=>{const pl=G.player,enemy=G.bots.find(e=>e.team!==pl.team),mate=G.bots.find(e=>e.team===pl.team),old=G.ents;G.ents=[pl,enemy,mate];markSpotted(enemy,pl.team,G.now);let radarEnemy=0,radarFriend=0,mapEnemy=0,mapFriend=0;const arc=rg.arc;rg.arc=function(...a){if(a[2]===3.6){if(this.fillStyle==='#d42a2a')radarEnemy++;if(this.fillStyle==='#2d6cb3')radarFriend++}return arc.apply(this,a)};drawRadar();rg.arc=arc;const g=$('tacticalMap').getContext('2d'),orig=g.arc;g.arc=function(...a){if(a[2]===5){if(this.fillStyle==='#d42a2a')mapEnemy++;if(this.fillStyle==='#2d6cb3')mapFriend++}return orig.apply(this,a)};drawTactical();g.arc=orig;G.ents=old;return{radarEnemy,radarFriend,mapEnemy,mapFriend}});yes(!dots.radarEnemy&&!dots.mapEnemy&&dots.radarFriend===1&&dots.mapFriend===1,'both maps hide all enemies while retaining teammates',dots);
await p.evaluate(()=>{const pl=G.player,e=G.bots.find(b=>b.team!==pl.team);kill(pl,e,'ak',false);G.deathCam.t=3;updateCamera(.016);updateHUD(.2)});const first=await p.evaluate(()=>G.spec.name);await p.click('#specNext');const next=await p.evaluate(()=>G.spec.name);yes(first!==next,'actual next-observer button switches living teammate');await p.click('#specPrev');yes(await p.evaluate(n=>G.spec.name===n,first),'previous-observer button returns to prior teammate');await p.keyboard.press('ArrowRight');yes(await p.evaluate(n=>G.spec.name!==n,first),'arrow key switches observer without pointer lock');
await p.evaluate(()=>{G.mode='range';startMatch();G.set.aimMode='trackpad';G.set.sens=1;G.player.pitch=0});await frames(p,60);await p.mouse.move(400,320);const start=await p.evaluate(()=>G.player.yaw);await p.mouse.move(420,320);const moved=await p.evaluate(()=>G.player.yaw);yes(Math.abs((start-moved)-.021)<.0002,'trackpad fallback uses predictable CSS cursor delta',{start,moved});const drift=await p.evaluate(()=>G.player.yaw);await frames(p,120);yes(await p.evaluate(y=>G.player.yaw===y,drift),'aim has no residual motion after events stop');const anomaly=await p.evaluate(()=>{const c=$('c'),y=G.player.yaw;resetLook();c.dispatchEvent(new MouseEvent('mousemove',{bubbles:true,clientX:100,clientY:100,movementX:999}));c.dispatchEvent(new MouseEvent('mousemove',{bubbles:true,clientX:102,clientY:100,movementX:999}));const d=y-G.player.yaw;c.dispatchEvent(new MouseEvent('mousemove',{bubbles:true,clientX:900,clientY:100}));const a=G.player.yaw;c.dispatchEvent(new MouseEvent('mousemove',{bubbles:true,clientX:902,clientY:100}));return{d,recovered:a-G.player.yaw}});yes(Math.abs(anomaly.d-.0021)<.0001&&Math.abs(anomaly.recovered-.0021)<.0001,'unlocked movement ignores raw-unit mismatch and recovers after outlier',anomaly);const clutch=await p.evaluate(()=>G.player.yaw);await p.keyboard.down('KeyH');await p.mouse.move(300,300);await p.mouse.move(600,350);await p.keyboard.up('KeyH');yes(await p.evaluate(y=>G.player.yaw===y,clutch),'H clutch permits cursor recentering without moving aim');const gun=await p.evaluate(()=>G.player.cur);await p.mouse.wheel(0,500);yes(await p.evaluate(k=>G.player.cur===k,gun),'trackpad wheel inertia cannot cycle guns');
const ammo=await p.evaluate(()=>G.player.ammo[G.player.cur].mag);await p.keyboard.down('KeyZ');await frames(p,1);await p.keyboard.up('KeyZ');yes(await p.evaluate(n=>G.player.ammo[G.player.cur].mag===n-1&&!G.fire,ammo),'keyboard Z fires and releases cleanly for trackpad use');
for(const key of ['m4','viper']){await p.evaluate(k=>{giveWeapon(G.player,k);switchTo(k)},key);await frames(p,60);await p.keyboard.press('KeyV');await frames(p,45);const a=await p.evaluate(()=>({scoped:G.player.scoped,fov:camera.fov,optic:$('optic').className,mask:$('scope').className,gun:VM.root.visible,rect:$('optic').getBoundingClientRect().toJSON()}));yes(a.scoped===1&&a.fov>=63&&a.fov<=71&&a.optic.includes('on')&&!a.mask.includes('on')&&a.gun,'low magnification optic keeps weapon and peripheral vision: '+key,a);yes(Math.abs(a.rect.x+a.rect.width/2-640)<1&&Math.abs(a.rect.y+a.rect.height/2-400)<1,'optic reticle centered: '+key);await p.keyboard.press('KeyZ');await frames(p,1);yes(await p.evaluate(()=>G.player.scoped===1),'automatic weapon keeps optic after firing: '+key);await p.screenshot({path:path.join(out,'optic-'+key+'.png')})}
await p.evaluate(()=>{giveWeapon(G.player,'awp');switchTo('awp')});await frames(p,70);await p.keyboard.press('KeyV');await frames(p,1);const early=await p.evaluate(()=>curSpread(G.player,WEAPONS.awp));await frames(p,30);const settled=await p.evaluate(()=>({spread:curSpread(G.player,WEAPONS.awp),fov:camera.fov}));yes(early>settled.spread*10&&Math.abs(settled.fov-46)<.1,'sniper has visible settle time and reduced first zoom',{early,settled});await p.keyboard.press('KeyV');await frames(p,40);yes(await p.evaluate(()=>Math.abs(camera.fov-26)<.1),'sniper second zoom capped at 26 degree FOV');await p.screenshot({path:path.join(out,'optic-awp.png')});
yes(!errors.length,'no page errors',errors);fs.writeFileSync(path.join(out,'feedback-check.json'),JSON.stringify({checks,errors,count:checks.length},null,2));console.log(JSON.stringify({checks,errors,count:checks.length},null,2));console.log('FEEDBACK CHECK OK')})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});
