#!/usr/bin/env node
/* R05 cross-session UI and delayed cosmetic callback regression. --baseline records observed failures. */
const fs=require('fs'),path=require('path'),http=require('http'),ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'outputs/revision-05/lifecycle'),baseline=process.argv.includes('--baseline');
let pw;for(const id of ['playwright','playwright-core','/Users/bing/Developer/codex-tools/npm-global/lib/node_modules/@playwright/cli/node_modules/playwright-core'])try{pw=require(id);break}catch(_){}if(!pw)throw Error('Playwright unavailable');
const server=http.createServer((req,res)=>{let f=path.join(ROOT,decodeURIComponent(req.url.split('?')[0]));if(f.endsWith('/'))f+='index.html';if(!f.startsWith(ROOT+path.sep)||!fs.existsSync(f)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(res)}),checks=[],errors=[];let browser;
function check(ok,name,evidence){checks.push({name,pass:!!ok,evidence});}
(async()=>{fs.mkdirSync(OUT,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await pw.chromium.launch({headless:true,args:['--use-angle=metal','--use-gl=angle','--ignore-gpu-blocklist']});const p=await browser.newPage({viewport:{width:1366,height:768}});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{requestAnimationFrame=()=>0;Element.prototype.requestFullscreen=()=>Promise.reject()});await p.goto(`http://127.0.0.1:${server.address().port}/?auto`);await p.waitForFunction(()=>$('menu').classList.contains('on'));
const step=n=>p.evaluate(n=>{for(let i=0;i<n;i++)frame(1/60)},n);
await p.click('#looksBtn');await p.keyboard.press('Escape');check(await p.evaluate(()=>!$('looks').classList.contains('on')),'Escape closes appearance dialog');await p.evaluate(()=>$('looksClose').click());await p.click('#armoryBtn');await p.keyboard.press('Escape');check(await p.evaluate(()=>!$('armory').classList.contains('on')),'Escape closes armory dialog');await p.evaluate(()=>$('armoryClose').click());
await p.click('#optMode [data-v="dm"]');await p.click('#start');await p.keyboard.press('KeyB');await p.click('#buyGrid [data-k="m4"]');await p.click('#buyClose');await step(80);
await p.evaluate(()=>{G.set.vol=0;PROG.data.kills.m4=9;delete PROG.data.skin.m4;const victim=G.bots.find(b=>b.team!==G.team);victim.spawnProtectedUntil=0;hurt(victim,1000,G.player,'m4','chest');G.player.ammo.m4.mag=7});await p.keyboard.press('KeyR');await step(20);const reloading=await p.evaluate(()=>({end:G.player.reloadEnd,draw:G.player.drawEnd,mag:G.player.ammo.m4.mag,pose:VM.reloadT,skin:PROG.skin('m4')}));await p.waitForTimeout(1650);const after=await p.evaluate(()=>({end:G.player.reloadEnd,draw:G.player.drawEnd,mag:G.player.ammo.m4.mag,pose:VM.reloadT,skin:PROG.skin('m4')}));check(reloading.end>0&&after.end===reloading.end&&after.draw===reloading.draw&&after.pose===reloading.pose&&after.mag===reloading.mag,'mastery unlock preserves an in-progress reload',{before:reloading,after});await step(220);check(await p.evaluate(()=>G.player.ammo.m4.mag===WEAPONS.m4.mag&&G.player.reloadEnd<0),'reload completes after cosmetic unlock');
await p.keyboard.press('KeyB');await p.click('#buyGrid [data-k="awp"]');await p.click('#buyClose');await step(80);await p.keyboard.press('KeyV');await p.keyboard.press('KeyV');await step(50);await p.evaluate(()=>{PROG.data.kills.awp=9;delete PROG.data.skin.awp;const victim=G.bots.find(b=>b.team!==G.team&&b.alive);victim.spawnProtectedUntil=0;hurt(victim,1000,G.player,'awp','chest')});const scoped=await p.evaluate(()=>({scope:G.player.scoped,draw:G.player.drawEnd,next:G.player.nextFire}));await p.waitForTimeout(1650);check(await p.evaluate(s=>G.player.scoped===s.scope&&G.player.drawEnd===s.draw&&G.player.nextFire===s.next,scoped),'mastery unlock preserves zoom and firing deadline',scoped);
await p.keyboard.press('Escape');await p.click('#quit');await step(1);const menu=await p.evaluate(()=>({fov:camera.fov,expected:G.set.fov,trainLabel:$('trainMotion').textContent,scope:$('scope').className}));check(Math.abs(menu.fov-menu.expected)<.05,'leaving a scoped match restores menu camera FOV',menu);await p.screenshot({path:path.join(OUT,baseline?'baseline-menu.png':'final-menu.png')});
await p.click('#optMode [data-v="range"]');await p.click('#start');await step(60);await p.keyboard.press('KeyY');await p.keyboard.press('Escape');await p.click('#quit');await p.click('#start');await step(60);await p.keyboard.press('KeyM');const training=await p.evaluate(()=>({moving:TRAIN.moving,label:$('trainMotion').textContent}));check(training.label===(training.moving?'横移靶：开':'横移靶：关'),'new range session control agrees with movement mode',training);await p.screenshot({path:path.join(OUT,baseline?'baseline-training.png':'final-training.png')});
await p.keyboard.press('Escape');await p.keyboard.press('Escape');await p.click('#quit');await p.click('#optTeam [data-v="red"]');await p.click('#start');await p.keyboard.press('Escape');await p.click('#quit');await p.click('#optMode [data-v="comp"]');const side=await p.evaluate(()=>({selected:document.querySelector('#optTeam .sel').dataset.v,team:G.team}));check(side.team==='red'&&side.selected===side.team,'range exit preserves selected competitive side',side);await p.click('#start');check(await p.evaluate(()=>G.player.team==='red'),'next competitive match joins the side selected in the menu');
await p.evaluate(()=>{G.noLock=false;window.originalPointerRequest=renderer.domElement.requestPointerLock;window.rejectedRequests=0;renderer.domElement.requestPointerLock=()=>{rejectedRequests++;return Promise.reject(new DOMException('temporary rate limit','NotAllowedError'))}});await step(10);await p.click('#captureMouse');await p.waitForTimeout(30);await step(10);const retry=await p.evaluate(()=>({noLock:G.noLock,pending:G.lockPending,button:!$('captureMouse').hidden,requests:rejectedRequests}));check(!retry.noLock&&!retry.pending&&retry.button&&retry.requests===1,'temporary pointer-lock denial keeps one-request retry without forced fallback',retry);await p.evaluate(()=>{renderer.domElement.requestPointerLock=originalPointerRequest;G.noLock=true});
check(!errors.length,'no page errors',errors);const result={baseline,checks,errors,passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass).length};fs.writeFileSync(path.join(OUT,baseline?'baseline.json':'final.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(result.failed&&!baseline)process.exitCode=1;} )().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});
