#!/usr/bin/env node
/* Revision 03 behavioral regression: real UI/input plus controlled world fixtures, no performance claims. */
const fs = require('fs'), path = require('path'), http = require('http');
const ROOT = path.resolve(__dirname, '..'), checks = [], failures = [], errors = [];
function loadPW() { for (const p of [process.env.PLAYWRIGHT, 'playwright', 'playwright-core', '/Users/bing/Developer/codex-tools/npm-global/lib/node_modules/@playwright/cli/node_modules/playwright-core'].filter(Boolean)) try { return require(p); } catch (_) {} throw Error('Playwright unavailable'); }
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.woff2': 'font/woff2' };
const server = http.createServer((q, r) => { let f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (f.endsWith('/')) f += 'index.html'; if (!f.startsWith(ROOT + path.sep) || !fs.existsSync(f)) { r.writeHead(404); return r.end(); } r.setHeader('Content-Type', mime[path.extname(f)] || 'application/octet-stream'); fs.createReadStream(f).pipe(r); });
let browser, url;
const yes = (v, text, data) => { if (!v) throw Error(text + (data ? ': ' + JSON.stringify(data) : '')); checks.push(text); };
async function test(name, fn) { process.stdout.write(name + ' ... '); try { await fn(); console.log('OK'); } catch (e) { failures.push({ name, error: e.message }); console.log('FAIL: ' + e.message.split('\n')[0]); } }
async function open(mobile = false) { const p = await browser.newPage({ viewport: mobile ? { width: 844, height: 390 } : { width: 1280, height: 720 }, ...(mobile ? { isMobile: true, hasTouch: true } : {}) }); p.on('pageerror', e => errors.push(e.message)); p.on('console', m => { if (m.type() === 'error' && !/Pointer Lock|pointer lock/i.test(m.text())) errors.push(m.text()); }); await p.addInitScript(() => { window.requestAnimationFrame = () => 0; Element.prototype.requestFullscreen = () => Promise.reject(); }); await p.goto(url + (mobile ? '/?auto&touch' : '/?auto')); await p.waitForFunction(() => document.getElementById('menu').classList.contains('on')); await p.evaluate(() => { G.manualStep = true; G.set.vol = 0; Math.random = rng(93603); }); return p; }
async function step(p, seconds) { await p.evaluate(s => { for (let i = 0; i < Math.round(s * 60); i++) frame(1 / 60); }, seconds); }
async function shot(p, pitch = null) { await p.mouse.move(640, 360); if (pitch !== null) await p.evaluate(t => { G.player.pitch = t; }, pitch); await p.mouse.down(); await step(p, 1 / 60); await p.mouse.up(); }
async function restartMode(p, mode) { await p.evaluate(m => { G.mode = m; G.set.battleSize = '5'; startMatch(); }, mode); }
(async () => {
  await new Promise(ok => server.listen(0, '127.0.0.1', ok)); url = `http://127.0.0.1:${server.address().port}`; browser = await loadPW().chromium.launch({ headless: true, args: ['--use-angle=metal', '--use-gl=angle', '--ignore-gpu-blocklist'] });
  const p = await open();
  await test('menu training guard', async () => { await p.click('#optMode [data-v="range"]'); await p.click('#mapPreview'); yes(!await p.locator('#trainStart').isVisible(), 'menu map preview hides training actions before player exists'); const a = await p.evaluate(() => ({ reset: TRAIN.reset(true), moving: TRAIN.setMoving(true), active: TRAIN.active, player: G.player })); yes(!a.active && !a.player, 'training entrypoints safely reject a menu-only session', a); await p.click('#mapClose'); });
  await p.click('#start'); await step(p, 1);
  await test('training real bullet', async () => { await p.keyboard.press('KeyT'); await p.mouse.move(640, 360); await p.evaluate(() => { const p = G.player, e = G.bots[0]; p.yaw = Math.PI; p.pitch = Math.atan2(e.pos.y + 1.12 - p.pos.y - eyeY(p), e.pos.z - p.pos.z); }); const before = await p.evaluate(() => G.player.ammo.ak.mag); await shot(p); const a = await p.evaluate(() => ({ ...TRAIN.snapshot(), mag: G.player.ammo.ak.mag, targetHP: G.bots[0].hp })); yes(a.shots === 1 && a.hits === 1 && a.damage > 0 && a.targetHP < 100 && a.mag === before - 1, 'mouse shot consumes ammo, damages target and records one training hit', a); await step(p, .35); await shot(p, 1.2); const b = await p.evaluate(() => TRAIN.snapshot()); yes(b.shots === 2 && b.hits === 1 && b.accuracy === 50, 'missed live shot lowers training accuracy instead of counting a hit', b); });
  await test('training modal clock', async () => { await p.keyboard.press('KeyM'); const a = await p.evaluate(() => TRAIN.left); await step(p, 2); yes(await p.evaluate(t => TRAIN.left === t, a), 'opening map suspends training countdown'); await p.click('#mapClose'); await p.keyboard.press('KeyB'); const b = await p.evaluate(() => TRAIN.left); await step(p, 2); yes(await p.evaluate(t => TRAIN.left === t, b), 'buy overlay suspends training countdown'); await p.click('#buyClose'); await p.keyboard.press('Escape'); const c = await p.evaluate(() => TRAIN.left); await step(p, 2); yes(await p.evaluate(t => TRAIN.left === t, c), 'pause suspends training countdown'); await p.click('#resume'); await step(p, 1); yes(await p.evaluate(t => TRAIN.left < t - .9, c), 'closing overlays resumes countdown'); });
  await test('shotgun per trigger', async () => { await p.keyboard.press('KeyB'); await p.click('#buyGrid [data-k="nova"]'); await p.click('#buyClose'); await step(p, .8); await p.keyboard.press('KeyT'); await p.mouse.move(640, 360); await p.evaluate(() => { const p = G.player, e = G.bots[0]; p.pos.set(e.pos.x, 0, e.pos.z - 2.5); p.yaw = Math.PI; p.pitch = Math.atan2(1.1 - eyeY(p), 2.5); }); await shot(p); const a = await p.evaluate(() => TRAIN.snapshot()); yes(a.shots === 1 && a.hits === 1 && a.damage > 50 && a.accuracy === 100, 'shotgun pellets contribute damage but one trigger produces one recorded hit', a); });
  await test('30 second completion and stat freeze', async () => { await p.keyboard.press('KeyT'); await step(p, 1); await p.mouse.move(640, 360); await p.evaluate(() => { const p = G.player, e = G.bots[0]; p.yaw = Math.PI; p.pitch = Math.atan2(1.1 - eyeY(p), e.pos.z - p.pos.z); }); await shot(p); await step(p, 30.1); const before = await p.evaluate(() => TRAIN.snapshot()); yes(!before.active && before.completed && before.seconds === 0 && before.shots === 1 && before.hits === 1, 'full thirty-second drill finishes with measured firing result', before); await shot(p, 1.2); const after = await p.evaluate(() => TRAIN.snapshot()); yes(JSON.stringify(before) === JSON.stringify(after), 'post-completion firing leaves published training result unchanged'); await p.keyboard.press('KeyT'); const reset = await p.evaluate(() => TRAIN.snapshot()); yes(reset.active && reset.seconds === 30 && !reset.shots && !reset.hits && !reset.damage, 'T restarts a completed drill with cleared counters'); });
  await test('range grenade exclusion and respawn', async () => { const a = await p.evaluate(() => { const before = TRAIN.snapshot(), e = G.bots[0]; hurt(e, 999, G.player, 'he', 'chest'); hurt(G.player, 999, G.player, 'he', 'chest'); frame(1 / 60); return { before, after: TRAIN.snapshot(), alive: G.player.alive, hp: G.player.hp }; }); yes(a.after.hits === a.before.hits && a.after.kills === a.before.kills && a.after.damage === a.before.damage, 'explosive damage does not inflate gun-training statistics', a); yes(a.alive && a.hp === 100, 'range self-elimination recovers a usable player'); });
  await test('mode change clears active drill', async () => { await p.keyboard.press('Escape'); await p.click('#quit'); await p.click('#optMode [data-v="dm"]'); await p.click('#start'); await step(p, .2); yes(await p.evaluate(() => G.mode === 'dm' && !TRAIN.active && $('training').hidden), 'real menu mode change removes running training state and HUD'); });
  await test('deathmatch protection and cleanup', async () => { await restartMode(p, 'dm'); const protectedHP = await p.evaluate(() => { const p = G.player, e = G.bots.find(b => b.team !== p.team); hurt(p, 90, e, 'ak', 'head'); return p.hp; }); yes(protectedHP === 100, 'fresh deathmatch spawn rejects enemy damage'); await step(p, .6); await shot(p, 1.2); const attacked = await p.evaluate(() => { const p = G.player, e = G.bots.find(b => b.team !== p.team); const protectedNow = G.now < p.spawnProtectedUntil; hurt(p, 20, e, 'ak', 'chest'); return { protectedNow, hp: p.hp }; }); yes(!attacked.protectedNow && attacked.hp < 100, 'firing during spawn protection cancels it before subsequent enemy damage', attacked); await p.keyboard.down('KeyW'); await p.mouse.down(); await p.evaluate(() => { const p = G.player, e = G.bots.find(b => b.team !== p.team); hurt(p, 9999, e, 'awp', 'head'); G.flashT = .8; }); const dead = await p.evaluate(() => ({ dead: !G.player.alive, report: $('report').classList.contains('on'), splats: G.splats.length })); yes(dead.dead && dead.report && dead.splats, 'lethal enemy damage produces death report and damage feedback', dead); await step(p, 3.05); await p.mouse.up(); await p.keyboard.up('KeyW'); const alive = await p.evaluate(() => ({ alive: G.player.alive, hp: G.player.hp, fire: G.fire, keys: Object.values(G.keys).some(Boolean), splats: G.splats.length, dirs: G.dmgDirs.length, flash: G.flashT, report: $('report').classList.contains('on'), protection: G.player.spawnProtectedUntil - G.now, pending: !!G.player.pending })); yes(alive.alive && alive.hp === 100 && !alive.fire && !alive.keys && !alive.splats && !alive.dirs && !alive.flash && !alive.report && !alive.pending && alive.protection > 0, 'deathmatch respawn clears injury overlays and held input with fresh protection', alive); });
  await test('round economy and sealed damage', async () => { await restartMode(p, 'comp'); await p.evaluate(() => { G.player.money = 10000; }); await p.keyboard.press('KeyB'); const budget = await p.locator('#buyBudget').innerText(); yes(budget.includes('1900'), 'first-loss budget displays actual 1900 subsidy'); for (const k of ['ak', 'armor', 'smoke', 'deagle']) await p.click(`#buyGrid [data-k="${k}"]`); const cash = await p.evaluate(() => ({ money: G.player.money, preset: G.set.lastBuy.slice() })); yes(cash.money === 5300 && cash.preset.length === 4, 'four real purchase clicks deduct exact 4700 and save full configuration', cash); await p.click('#buyClose'); await step(p, 6.1); await p.evaluate(() => { G.timer = .001; frame(.01); }); const a = await p.evaluate(() => { const e = G.bots.find(b => b.team !== G.player.team), before = { hp: e.hp, money: G.player.money, kills: G.player.kills, stats: JSON.stringify([...PROG.rs]), score: JSON.stringify(G.score) }; hurt(e, 999, G.player, 'ak', 'head'); buy('m4'); return { state: G.state, before, after: { hp: e.hp, money: G.player.money, kills: G.player.kills, stats: JSON.stringify([...PROG.rs]), score: JSON.stringify(G.score) }, cur: G.player.cur }; }); yes(a.state === 'roundEnd' && a.before.money === 8550 && a.cur === 'deagle' && JSON.stringify(a.before) === JSON.stringify(a.after), 'timer settles round once; late damage and purchases cannot change money, result or stats', a); });
  await test('death, next-round rebuy transaction', async () => { await p.waitForTimeout(950); await step(p, 5.2); await step(p, 6.2); const a = await p.evaluate(() => { const enemy = G.bots.find(b => b.team !== G.player.team); for (const e of G.ents.filter(e => e.team === G.player.team && e !== G.player)) hurt(e, 99999, enemy, 'awp', 'head'); hurt(G.player, 99999, enemy, 'awp', 'head'); return { dead: !G.player.alive, helmet: G.player.helmet, armor: G.player.armor, primary: G.player.inv[1], state: G.state }; }); yes(a.dead && !a.helmet && !a.armor && !a.primary && a.state === 'roundEnd', 'team wipe removes dead player equipment before the next round', a); await p.waitForTimeout(950); await step(p, 5.2); await p.evaluate(() => { G.player.money = 4699; }); await p.keyboard.press('KeyB'); yes(await p.locator('#rebuy').isDisabled(), 'insufficient funds disable complete-preset rebuy'); const b = await p.evaluate(() => { rebuy(); return { money: G.player.money, primary: G.player.inv[1], armor: G.player.armor, bill: rebuyBill() }; }); yes(b.money === 4699 && !b.primary && !b.armor && b.bill.cost === 4700, 'failed rebuy buys no partial items and spends no money', b); await p.evaluate(() => { G.player.money = 4700; drawBuy(); }); await p.click('#rebuy'); const c = await p.evaluate(() => ({ money: G.player.money, primary: G.player.inv[1], secondary: G.player.inv[2], armor: G.player.armor, helmet: G.player.helmet, smoke: G.player.nades.smoke, bill: rebuyBill(), preset: G.set.lastBuy })); yes(c.money === 0 && c.primary === 'ak' && c.secondary === 'deagle' && c.armor === 100 && c.helmet && c.smoke === 1 && c.bill.cost === 0 && c.preset.length === 4, 'one rebuy click restores all lost equipment for exact cost', c); yes(await p.locator('#rebuy').isDisabled(), 'completed preset cannot be charged twice'); await p.click('#buyClose'); });
  await test('radar hides enemy intelligence', async () => { const a = await p.evaluate(() => { G.mode = 'range'; startMatch(); const p = G.player, e = G.bots[0]; for (const b of G.bots) b.alive = b === e; p.pos.set(0,0,30); p.yaw = Math.PI; e.pos.set(0,0,36); e.spottedBy = {}; G._spotT = G.now - 1; frame(.25); const old = { ...e.spottedBy[p.team] }; e.pos.set(20,0,30); frame(.3); const record = () => { const arcs = [], orig = rg.arc; rg.arc = function(...args) { if (this.fillStyle === '#d42a2a') arcs.push(args.slice(0,3)); return orig.apply(this,args); }; drawRadar(); rg.arc = orig; return arcs; }; const last = record(); frame(1.6); const expired = record(); markSpotted(e, 'red', G.now); const otherTeam = record(); return { old, last, expired, otherTeam, now:G.now }; }); yes(a.old.x === 0 && a.old.z === 36 && a.last.length === 0, 'actual radar canvas hides even a fresh enemy sighting', a); yes(!a.expired.length && !a.otherTeam.length, 'expired sightings and enemy-team-only intelligence produce no radar marker', a); });
  await p.close();
  const m = await open(true);
  await test('mobile training controls', async () => { await m.locator('#optMode [data-v="range"]').tap(); await m.locator('#start').tap(); await step(m, .8); await m.locator('#tTop [data-b="map"]').tap(); yes(await m.locator('#trainMotion').isVisible(), 'touch map exposes training controls in a live range'); await m.locator('#trainMotion').tap(); yes(await m.evaluate(() => TRAIN.moving && !TRAIN.active), 'touch moving-target toggle updates drill mode'); await m.locator('#trainStart').tap(); yes(await m.evaluate(() => TRAIN.active && !G.mapOpen), 'touch start button closes map and begins thirty-second drill'); const before = await m.evaluate(() => G.bots[0].pos.x); await step(m, .7); yes(await m.evaluate(x => Math.abs(G.bots[0].pos.x - x) > .1, before), 'enabled target moves during actual simulation'); const layout = await m.evaluate(() => ({ viewport: innerWidth, scroll: document.documentElement.scrollWidth, text: $('training').textContent, hidden: $('training').hidden })); yes(layout.scroll === layout.viewport && !layout.hidden && layout.text.includes('横移'), 'landscape touch drill HUD fits the viewport and shows moving mode', layout); });
  await test('mobile timed drill requires manual fire', async () => { await m.locator('#tTop [data-b="map"]').tap(); await m.locator('#trainMotion').tap(); await m.locator('#trainStart').tap(); await m.evaluate(() => { G.set.autoFire = true; G.player.yaw = Math.PI; G.player.pitch = Math.atan2(1.12 - eyeY(G.player), 10); }); await step(m, .8); const a = await m.evaluate(() => ({ shots: TRAIN.shots, mag: G.player.ammo[G.player.cur].mag, auto: TOUCH.auto, setting: G.set.autoFire, aiming: TOUCH.aimOn })); yes(a.shots === 0 && a.mag === 30 && !a.auto && a.setting && a.aiming, 'timed drill suppresses automatic fire while target is acquired and preserves setting', a); const r = await m.locator('#tFire').boundingBox(), cdp = await m.context().newCDPSession(m); await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x:r.x+r.width/2,y:r.y+r.height/2 }] }); await step(m, .1); await cdp.send('Input.dispatchTouchEvent', { type:'touchEnd',touchPoints:[] }); const b = await m.evaluate(() => ({ shots:TRAIN.shots,hits:TRAIN.hits,mag:G.player.ammo[G.player.cur].mag })); yes(b.shots > 0 && b.hits > 0 && b.mag < 30, 'real held touch fire still records shots and hits during timed drill', b); await m.evaluate(() => { TRAIN.left = .01; G.player.pitch = Math.atan2(1.12 - eyeY(G.player), 10); G.player.recP = G.player.recTP = G.player.recY = G.player.recTY = 0; }); await step(m, .6); const c = await m.evaluate(() => ({ active:TRAIN.active,completed:TRAIN.completed,setting:G.set.autoFire,mag:G.player.ammo[G.player.cur].mag })); yes(!c.active && c.completed && c.setting && c.mag < b.mag, 'saved automatic-fire preference resumes after timed drill completion', c); });
  await m.close();
  if (errors.length) failures.push({ name:'browser errors',error:[...new Set(errors)].join('\n') });
  const result = { checks, failures, errors }; fs.mkdirSync(path.join(ROOT,'outputs/revision-04'),{recursive:true}); fs.writeFileSync(path.join(ROOT,'outputs/revision-04/revision-check.json'),JSON.stringify(result,null,2)); console.log(JSON.stringify(result,null,2)); if (failures.length) throw Error('REVISION CHECK FAIL'); console.log('\nREVISION CHECK OK');
})().catch(e => { console.error(e.stack); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); server.close(); });
