#!/usr/bin/env node
/* R05 diagnostic soak. Real frame/AI/collision/objective updates; visual round-end slow motion
   is normalized and rendering sampled during acceleration. Scores include one idle player,
   so these runs diagnose progression and congestion, not competitive team balance.
   SOAK_SEEDS=501,502 SOAK_MAPS=papertown,warehouse,dunes SOAK_OUTPUT=... node tools/soak-check.js
   SOAK_ONLY=objectives runs controlled held-E/physical recovery cases without long matches.
   SOAK_SKIP_OBJECTIVES=1 skips held-E cases; the fixed paper-town corner regression remains. */
const fs=require('fs'),path=require('path'),http=require('http');
const ROOT=path.resolve(__dirname,'..'),OUT=process.env.SOAK_OUTPUT||path.join(ROOT,'outputs/revision-05/systems'),SEEDS=(process.env.SOAK_SEEDS||'501,502').split(',').map(Number),MAPS=(process.env.SOAK_MAPS||'papertown,warehouse,dunes').split(',');
function loadPW(){for(const p of [process.env.PLAYWRIGHT,'playwright','playwright-core','/Users/bing/Developer/codex-tools/npm-global/lib/node_modules/@playwright/cli/node_modules/playwright-core'].filter(Boolean))try{return require(p)}catch(e){}throw Error('Playwright unavailable')}
const server=http.createServer((q,r)=>{let f=path.join(ROOT,decodeURIComponent(q.url.split('?')[0]));if(f.endsWith('/'))f+='index.html';if(!f.startsWith(ROOT+path.sep)||!fs.existsSync(f)){r.writeHead(404);return r.end()}r.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(f).pipe(r)});let browser;
(async()=>{fs.mkdirSync(OUT,{recursive:true});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const url='http://127.0.0.1:'+server.address().port;browser=await loadPW().chromium.launch({headless:true,args:['--use-angle=metal','--use-gl=angle','--ignore-gpu-blocklist']});const results=[],errors=[];
if(!process.env.SOAK_ONLY)for(const map of MAPS)for(const seed of SEEDS){const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push({map,seed,message:e.message}));await page.addInitScript(()=>window.requestAnimationFrame=()=>0);await page.goto(url+'/?auto&map='+map);await page.waitForFunction(()=>$('menu').classList.contains('on'),null,{polling:100});
await page.evaluate(({seed})=>{Math.random=rng(seed);G.set.battleSize='12';G.set.quality='low';applyQuality();G.mode='comp';G.team=seed%2?'blue':'red';G.diff=1;G.manualStep=true;G.set.vol=0;const s=window.SOAK={map:MAP.id,seed,team:G.team,frames:0,rounds:[],stalls:[],stallResolutions:[],noGoals:[],transitions:[],maxNearPairs:0,nearPairSamples:0,aliveSamples:0,pathSamples:0,blindSamples:0,fightingSamples:0,yieldSamples:0,noDefuserSeconds:0,plantAttempts:0,plantAborts:0,defuseAttempts:0,defuseAborts:0,handovers:0,invalid:[],trace:[]};const snapshots=new Map();window.SOAK_SNAP=snapshots;const er=window.endRound;window.endRound=(win,reason)=>{if(G.state==='live')s.rounds.push({round:G.round,at:+G.now.toFixed(2),win,reason,bomb:BOMB.state,alive:G.ents.filter(e=>e.alive).reduce((a,e)=>(a[e.team]++,a),{red:0,blue:0}),kills:G.bots.reduce((n,b)=>n+b.kills,0)});return er(win,reason)};const interact=window.entInteract;window.entInteract=(e,want,dt)=>{const old=e.act,oldType=old&&old.type;interact(e,want,dt);const cur=e.act;if(!oldType&&cur)s[cur.type+'Attempts']++;if(oldType&&!cur&&(oldType==='plant'?BOMB.state==='carried':BOMB.state==='planted'))s[oldType+'Aborts']++};const render=renderer.render.bind(renderer);renderer.render=(...a)=>{if(s.frames%30===0||s.forceDraw)render(...a)};startMatch();s.started=G.now;s.lastBomb=BOMB.state;s.lastRound=G.round;}, {seed});
let snap;for(let batch=0;batch<160;batch++){snap=await page.evaluate(()=>{const s=SOAK,snapshots=SOAK_SNAP;for(let i=0;i<500&&G.state!=='matchEnd';i++){G.timescale=1;frame(1/30);s.frames++;if(G.state==='live'&&BOMB.carrier===G.player&&passCore())s.handovers++;if(s.lastBomb!==BOMB.state||s.lastRound!==G.round){s.transitions.push({at:+G.now.toFixed(2),round:G.round,from:s.lastBomb,to:BOMB.state,carrier:BOMB.carrier&&BOMB.carrier.name,pos:BOMB.pos.toArray()});s.lastBomb=BOMB.state;s.lastRound=G.round;}if(s.frames%30||G.state!=='live')continue;const living=G.bots.filter(b=>b.alive);let pairs=0;for(let a=0;a<living.length;a++)for(let b=a+1;b<living.length;b++)if(living[a].team===living[b].team&&living[a].pos.distanceTo(living[b].pos)<1)pairs++;s.maxNearPairs=Math.max(s.maxNearPairs,pairs);s.nearPairSamples+=pairs;
for(const b of living){s.aliveSamples++;s.pathSamples+=!!b.path;s.blindSamples+=G.now<(b.blindT||0);s.fightingSamples+=!!b.targetVis;s.yieldSamples+=!!b.yielding;const key=b.name+':'+b.deaths+':'+G.round,old=snapshots.get(key),goal=b.coverPlan?.path[b.coverPlan.pi]||b.path?.[b.pi],moving=goal&&Math.hypot(goal.x-b.pos.x,goal.z-b.pos.z)>1&&!b.targetVis&&!b.act&&G.now>=(b.blindT||0)&&G.now>=(b.flashAvoidT||0),d=old?Math.hypot(b.pos.x-old.x,b.pos.z-old.z):10,stuck=moving&&d<.3?(old?.stuck||0)+1:0,noGoal=!b.path&&!b.coverPlan&&!b.target&&!b.act&&b.holdYaw==null&&G.now>b.waitT+2?(old?.noGoal||0)+1:0;const entry={at:+G.now.toFixed(2),round:G.round,name:b.name,team:b.team,pos:b.pos.toArray(),intent:b.intent,goal,carrier:BOMB.carrier===b,bomb:BOMB.state,act:b.act,target:b.target?.name,targetVis:b.targetVis,yielding:b.yielding,hitWall:b.hitWall,pi:b.pi,path:b.path?.slice(Math.max(0,b.pi-1),b.pi+3),neighbors:living.filter(o=>o!==b&&o.pos.distanceTo(b.pos)<3).map(o=>({name:o.name,team:o.team,pos:o.pos.toArray(),vel:o.vel.toArray(),path:o.path?.[o.pi],waitT:o.waitT,holdYaw:o.holdYaw,target:o.target?.name,yielding:o.yielding}))};if(old?.stuck>=8&&!stuck)s.stallResolutions.push({name:b.name,round:G.round,at:+G.now.toFixed(2),seconds:old.stuck,pos:b.pos.toArray(),intent:b.intent});if(stuck===8)s.stalls.push(entry);if(noGoal===4)s.noGoals.push(entry);snapshots.set(key,{x:b.pos.x,z:b.pos.z,stuck,noGoal});if(!b.pos.toArray().every(Number.isFinite)||b.pos.x<MAP.bounds.x1-.5||b.pos.x>MAP.bounds.x2+.5||b.pos.z<MAP.bounds.z1-.5||b.pos.z>MAP.bounds.z2+.5)s.invalid.push(entry);}
if(BOMB.state==='planted'&&living.some(b=>b.team==='blue')&&!living.some(b=>b.team==='blue'&&(b.act?.type==='defuse'||b.intent==='回防拆核')))s.noDefuserSeconds++;if(s.frames%300===0)s.trace.push({at:+G.now.toFixed(1),round:G.round,timer:+G.timer.toFixed(1),bomb:BOMB.state,bombT:+BOMB.t.toFixed(1),alive:living.length,defuser:BOMB.defuser?.name,carrier:BOMB.carrier?.name});}
return{done:G.state==='matchEnd',round:G.round,elapsed:+(G.now-s.started).toFixed(1),score:{...G.score},frames:s.frames,stalls:s.stalls.length,noGoals:s.noGoals.length,invalid:s.invalid.length};});if(batch%10===0||snap.done)console.log(JSON.stringify({map,seed,...snap}));if(snap.done||snap.invalid)break;}
const result=await page.evaluate(()=>({...SOAK,state:G.state,score:{...G.score},elapsed:+(G.now-SOAK.started).toFixed(2),currentBots:G.bots.filter(b=>b.alive).map(b=>({name:b.name,pos:b.pos.toArray(),intent:b.intent,path:b.path?.slice(b.pi,b.pi+2),target:b.target?.name,act:b.act})),text:JSON.parse(render_game_to_text())}));results.push(result);fs.writeFileSync(path.join(OUT,map+'-'+seed+'.json'),JSON.stringify(result,null,2));await page.evaluate(()=>{SOAK.forceDraw=true;frame(0)});await page.screenshot({path:path.join(OUT,map+'-'+seed+'.png')});await page.close();}
const objectiveChecks=process.env.SOAK_SKIP_OBJECTIVES?[]:await runObjectives(url,errors);const recoveryCheck=await runRecovery(url,errors);const summary={recoveryCheck,condition:'12v12 with 23 Bots and one idle player; fixed seeds; not a balance estimate',playerSides:[...new Set(results.map(r=>r.team))],objectiveChecks,results:results.map(r=>({map:r.map,seed:r.seed,team:r.team,state:r.state,seconds:r.elapsed,rounds:r.rounds.length,score:r.score,stalls:r.stalls.length,noGoals:r.noGoals.length,maxNearPairs:r.maxNearPairs,noDefuserSeconds:r.noDefuserSeconds,plantAttempts:r.plantAttempts,plantAborts:r.plantAborts,defuseAttempts:r.defuseAttempts,defuseAborts:r.defuseAborts,invalid:r.invalid.length})),errors};fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));if(errors.length||results.some(r=>r.state!=='matchEnd'||r.invalid.length))throw Error('SOAK CHECK FAIL');console.log('SOAK CHECK OK');})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});

async function runObjectives(url,errors){
 const fixtures={papertown:{pos:[-42.221,0,-35.85],yaw:-Math.PI/2},warehouse:{pos:[-33.679,0,-24.95],yaw:Math.PI/2},dunes:{pos:[32.679,0,-34.95],yaw:-Math.PI/2}},checks=[];
 const check=(v,n)=>{if(!v)throw Error(n);checks.push(n)};
 for(const map of MAPS){
  const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push({map,test:'objective',message:e.message}));await page.addInitScript(()=>window.requestAnimationFrame=()=>0);await page.goto(url+'/?auto&map='+map);await page.waitForFunction(()=>$('menu').classList.contains('on'));
  const setup=await page.evaluate(f=>{Math.random=rng(517);G.manualStep=true;G.mode='comp';G.team='red';G.set.battleSize='12';G.set.quality='low';applyQuality();startMatch();G.state='live';G.timer=100;G.set.vol=0;for(const b of G.bots)b.dummy=true;const p=G.player;p.pos.fromArray(f.pos);p.yaw=f.yaw;p.pitch=-.75;p.vel.set(0,0,0);p.onGround=true;BOMB.carrier=p;BOMB.state='carried';frame(0);return{legal:!entOverlap(p,p.pos.x,p.pos.y,p.pos.z,MAP.near(p.pos.x,p.pos.z)),site:siteAt(p.pos),canPlant:!!canPlant(p),player:p.pos.toArray()};},fixtures[map]);
  check(setup.legal&&setup.canPlant,map+': collision-free live site fixture can plant');await page.keyboard.down('e');await page.evaluate(()=>{for(let i=0;i<202;i++)frame(1/60)});await page.keyboard.up('e');const planted=await page.evaluate(()=>{const p=G.player,probe={hw:.29,hgt:.38};return{state:BOMB.state,site:BOMB.site,pos:BOMB.pos.toArray(),player:p.pos.toArray(),blocked:!!entOverlap(probe,BOMB.pos.x,BOMB.pos.y+.01,BOMB.pos.z,MAP.near(BOMB.pos.x,BOMB.pos.z)),supported:Math.abs(supportY({pos:BOMB.pos,hw:.29},MAP.near(BOMB.pos.x,BOMB.pos.z))-BOMB.pos.y)<.08,text:JSON.parse(render_game_to_text())}});check(planted.state==='planted',map+': actual held E completes the 3.2s plant');check(!planted.blocked&&planted.supported,map+': close-wall plant leaves visible supported core outside collision');await page.keyboard.down('s');await page.evaluate(()=>{for(let i=0;i<28;i++)frame(1/60)});await page.keyboard.up('s');await page.evaluate(()=>{for(let i=0;i<15;i++)frame(1/60)});await page.screenshot({path:path.join(OUT,map+'-safe-plant.png')});fs.writeFileSync(path.join(OUT,map+'-objective.json'),JSON.stringify({setup,planted},null,2));await page.close();
 }
 if(!MAPS.includes('papertown'))return checks;
 // One original pillar gives a real 1.51m occluded interaction across its 0.8m width.
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push({test:'defuse',message:e.message}));await page.addInitScript(()=>window.requestAnimationFrame=()=>0);await page.goto(url+'/?auto&map=papertown');await page.waitForFunction(()=>$('menu').classList.contains('on'));
 const prepare=async()=>page.evaluate(()=>{Math.random=rng(519);G.manualStep=true;G.mode='comp';G.team='blue';G.set.battleSize='12';G.set.quality='low';applyQuality();startMatch();G.state='live';G.timer=100;G.set.vol=0;for(const b of G.bots)b.dummy=true;const red=G.bots.find(b=>b.team==='red');Object.assign(red,{dummy:false,nextThink:1e9,target:null,targetVis:false,nade:null});red.pos.set(-42.221,0,-35.6);red.yaw=0;red.vel.set(0,0,0);red.onGround=true;BOMB.state='carried';BOMB.carrier=red;G.player.pos.set(-40.779,0,-35.6);G.player.yaw=Math.PI/2;G.player.pitch=-.4;G.player.vel.set(0,0,0);for(let i=0;i<202;i++)frame(1/60);red.dummy=true;red.pos.set(0,0,44);return{state:BOMB.state,bomb:BOMB.pos.toArray(),player:G.player.pos.toArray(),distance:G.player.pos.distanceTo(BOMB.pos),blocked:!segClear(G.player.pos.x,G.player.pos.y+eyeY(G.player),G.player.pos.z,BOMB.pos.x,BOMB.pos.y+.16,BOMB.pos.z),canDefuse:canDefuse(G.player)};});
 const before=await prepare();check(before.state==='planted'&&before.distance<1.9&&before.blocked,'actual Bot completes plant on other side of real pillar');check(!before.canDefuse,'nearby occluded core is not an interactable target');await page.keyboard.down('e');await page.evaluate(()=>{for(let i=0;i<382;i++)frame(1/60)});await page.keyboard.up('e');const blocked=await page.evaluate(()=>({state:BOMB.state,act:G.player.act,score:{...G.score},text:JSON.parse(render_game_to_text())}));check(blocked.state==='planted'&&!blocked.act&&blocked.score.blue===0,'6.36s of actual held E cannot defuse through pillar');await page.screenshot({path:path.join(OUT,'blocked-defuse.png')});
 await page.evaluate(()=>{G.player.yaw=0;G.player.pitch=-.4});await page.keyboard.down('w');await page.evaluate(()=>{for(let i=0;i<18;i++)frame(1/60)});await page.keyboard.up('w');await page.keyboard.down('a');await page.evaluate(()=>{for(let i=0;i<24;i++)frame(1/60)});await page.keyboard.up('a');await page.keyboard.down('s');await page.evaluate(()=>{for(let i=0;i<13;i++)frame(1/60)});await page.keyboard.up('s');await page.evaluate(()=>{for(let i=0;i<18;i++)frame(1/60)});const walked=await page.evaluate(()=>({pos:G.player.pos.toArray(),clear:canDefuse(G.player),legal:!entOverlap(G.player,G.player.pos.x,G.player.pos.y,G.player.pos.z,MAP.near(G.player.pos.x,G.player.pos.z))}));check(walked.clear&&walked.legal,'actual W/A/S movement reaches exposed side around pillar');await page.keyboard.down('e');await page.evaluate(()=>{for(let i=0;i<368;i++)frame(1/60)});await page.keyboard.up('e');const defused=await page.evaluate(()=>({state:BOMB.state,game:G.state,score:{...G.score},text:JSON.parse(render_game_to_text())}));check(defused.state==='defused'&&defused.score.blue===1&&defused.game==='roundEnd','held E on exposed side completes defuse and settles one blue round');await page.screenshot({path:path.join(OUT,'exposed-defuse.png')});
 await prepare();const botPath=await page.evaluate(()=>{G.player.pos.set(0,0,-46);const b=G.bots.find(e=>e.team==='blue');resetBotAwareness(b);Object.assign(b,{dummy:false,nextThink:1e9,target:null,targetVis:false,nade:null,path:null,waitT:0});b.pos.set(-40.779,0,-35.6);b.vel.set(0,0,0);const from=b.pos.clone(),samples=[];let firstAct=null;for(let i=0;i<720&&BOMB.state==='planted';i++){frame(1/60);if(b.act&&!firstAct)firstAct={at:(i+1)/60,pos:b.pos.toArray(),clear:segClear(b.pos.x,b.pos.y+eyeY(b),b.pos.z,BOMB.pos.x,BOMB.pos.y+.16,BOMB.pos.z)};if(i%30===0)samples.push({at:(i+1)/60,pos:b.pos.toArray(),act:b.act,intent:b.intent,path:b.path?.slice(b.pi,b.pi+2)});}return{from:from.toArray(),firstAct,displacement:b.pos.distanceTo(from),state:BOMB.state,score:{...G.score},samples};});check(botPath.firstAct&&botPath.firstAct.clear&&botPath.displacement>.6&&botPath.state==='defused','blue Bot navigates around occluding pillar and completes a visible defuse');fs.writeFileSync(path.join(OUT,'defuse-boundary.json'),JSON.stringify({before,blocked,walked,defused,botPath},null,2));await page.close();return checks;
}

async function runRecovery(url,errors){
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push({test:'corner-recovery',message:e.message}));await page.addInitScript(()=>window.requestAnimationFrame=()=>0);await page.goto(url+'/?auto&map=papertown');await page.waitForFunction(()=>$('menu').classList.contains('on'));
 const result=await page.evaluate(()=>{Math.random=rng(502);G.manualStep=true;G.mode='comp';G.team='blue';G.set.quality='low';applyQuality();startMatch();G.state='live';G.timer=100;for(const b of G.bots)b.dummy=true;G.player.pos.set(-4,0,-31);G.player.yaw=-.7;const b=G.bots.find(b=>b.team==='blue'),goal={x:18.5,z:-18.5};resetBotAwareness(b);Object.assign(b,{dummy:false,nextThink:1e9,target:null,targetVis:false,nade:null,path:null,waitT:0});b.pos.set(2.321,0,-26.821);b.vel.set(0,0,0);const initial=navPath(b.pos.x,b.pos.z,goal.x,goal.z);botObjective=()=>goal;const samples=[];let escapedAt=null,teleports=0,overlaps=0,previous=b.pos.clone();for(let i=0;i<600;i++){frame(1/30);if(b.pos.distanceTo(previous)>.4)teleports++;previous.copy(b.pos);if(entOverlap(b,b.pos.x,b.pos.y+.001,b.pos.z,MAP.near(b.pos.x,b.pos.z)))overlaps++;if(escapedAt===null&&b.pos.z>-25)escapedAt=(i+1)/30;if(i%30===0)samples.push({s:+((i+1)/30).toFixed(2),pos:b.pos.toArray(),path:b.path?.slice(b.pi,b.pi+3),stuck:b.stuckT,hitWall:b.hitWall});}return{initial,final:b.pos.toArray(),escapedAt,teleports,overlaps,goalDistance:Math.hypot(b.pos.x-goal.x,b.pos.z-goal.z),samples};});
 fs.writeFileSync(path.join(OUT,'corner-recovery.json'),JSON.stringify(result,null,2));await page.screenshot({path:path.join(OUT,'corner-recovery.png')});await page.close();if(result.escapedAt===null||result.escapedAt>6||result.teleports||result.overlaps||result.goalDistance>1)throw Error('corner recovery failed '+JSON.stringify(result));return{escapedAt:result.escapedAt,goalDistance:result.goalDistance,teleports:result.teleports,overlaps:result.overlaps};
}
