#!/usr/bin/env node
/* Revision 02 UI + roster + touch regression. Run: node tools/upgrade-check.js
   Native pointer lock is checked when supported; unavailable browser support is reported explicitly.
   --headed opens Chromium. Screenshots are optional: UPGRADE_SCREENSHOTS=/tmp/inkstrike-qa. */
const fs = require('fs'), path = require('path'), http = require('http');
const ROOT = path.resolve(__dirname, '..'), checks = [], errors = [], notes = [];
function loadPW() { for (const p of [process.env.PLAYWRIGHT, 'playwright', 'playwright-core', '/Users/bing/Developer/codex-tools/npm-global/lib/node_modules/@playwright/cli/node_modules/playwright-core'].filter(Boolean)) { try { return require(p); } catch (_) { } } throw Error('Playwright not found; set PLAYWRIGHT to an installed playwright/playwright-core package.'); }
function check(ok, label) { if (!ok) throw Error(label); checks.push(label); }
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.woff2': 'font/woff2' };
const server = http.createServer((q, r) => { let f = path.join(ROOT, decodeURIComponent(q.url.split('?')[0])); if (f.endsWith('/')) f += 'index.html'; if (!f.startsWith(ROOT + path.sep) || !fs.existsSync(f)) { r.writeHead(404); return r.end(); } r.setHeader('Content-Type', mime[path.extname(f)] || 'application/octet-stream'); fs.createReadStream(f).pipe(r); });
let browser;
async function capture(page, name) { if (!process.env.UPGRADE_SCREENSHOTS) return; fs.mkdirSync(process.env.UPGRADE_SCREENSHOTS, { recursive: true }); await page.screenshot({ path: path.join(process.env.UPGRADE_SCREENSHOTS, name + '.png') }); }
async function openPage(url, options = {}) { const page = await browser.newPage(options); page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error' && !/pointer lock|Pointer Lock/i.test(m.text())) errors.push(m.text()); }); await page.addInitScript(() => { window.requestAnimationFrame = () => 0; Element.prototype.requestFullscreen = () => Promise.reject(); }); await page.goto(url); await page.waitForFunction(() => document.getElementById('menu').classList.contains('on'), null, { timeout: 60000 }); return page; }
(async () => {
  await new Promise(ok => server.listen(0, '127.0.0.1', ok)); const url = `http://127.0.0.1:${server.address().port}`;
  browser = await loadPW().chromium.launch({ headless: !process.argv.includes('--headed'), args: ['--use-angle=metal', '--use-gl=angle', '--ignore-gpu-blocklist'] });
  const desktop = await openPage(url, { viewport: { width: 1440, height: 900 } });
  await desktop.click('#optSize [data-v="5"]'); await desktop.click('#start'); await desktop.waitForTimeout(150);
  const pointer = await desktop.evaluate(() => ({ native: !!document.pointerLockElement, fallback: G.noLock }));
  check(pointer.native || pointer.fallback, 'start enters native pointer lock or explicit fallback'); if (!pointer.native) notes.push('Native pointer lock unavailable in this Chromium session; fallback lifecycle validated.');
  await desktop.keyboard.press('KeyB'); await desktop.waitForTimeout(150);
  check(await desktop.evaluate(() => G.buyOpen && !G.paused && !document.pointerLockElement), 'B opens clickable purchase UI without pausing combat');
  await desktop.click('#buyGrid [data-k="deagle"]'); check(await desktop.evaluate(() => G.player.cur === 'deagle' && G.player.money === 100), 'desktop purchase equips weapon and deducts its exact cost');
  await desktop.click('#buyClose'); await desktop.waitForTimeout(150); check(await desktop.evaluate(() => !G.buyOpen && !G.paused && (G.noLock || !!document.pointerLockElement)), 'purchase close restores gameplay input');
  await desktop.keyboard.press('KeyM'); await desktop.keyboard.down('Space'); await desktop.keyboard.down('KeyC'); await desktop.keyboard.down('KeyE');
  check(await desktop.evaluate(() => { G.state = 'live'; const y = G.player.pos.y; updatePlayer(1 / 60); return G.mapOpen && !G.paused && G.player.pos.y === y && !G.keys.Space && !G.keys.KeyC && !G.keys.KeyE; }), 'map overlay blocks jump/crouch/interact input');
  for (const k of ['Space', 'KeyC', 'KeyE']) await desktop.keyboard.up(k); await desktop.click('#mapClose'); await desktop.waitForTimeout(150);
  check(await desktop.evaluate(() => !G.mapOpen && !G.paused && (G.noLock || !!document.pointerLockElement)), 'map close restores gameplay input');
  await desktop.keyboard.press('KeyM'); await desktop.keyboard.press('Escape'); await desktop.waitForTimeout(150); check(await desktop.evaluate(() => !G.mapOpen && !G.paused), 'Escape closes map before pausing');
  await desktop.keyboard.press('Escape'); await desktop.waitForTimeout(150); check(await desktop.evaluate(() => G.paused && $('pause').classList.contains('on') && !document.pointerLockElement), 'Escape pauses and releases pointer lock');
  await desktop.selectOption('#sQuality', 'low'); await desktop.locator('#sMotion').fill('0.6'); await desktop.locator('#sSens').fill('1.35');
  await desktop.click('#resume'); await desktop.waitForTimeout(150); check(await desktop.evaluate(() => !G.paused && (G.noLock || !!document.pointerLockElement)), 'resume restores gameplay input');
  await desktop.evaluate(() => { G.keys.KeyW = true; G.fire = true; dispatchEvent(new Event('blur')); }); check(await desktop.evaluate(() => G.paused && !G.fire && !Object.values(G.keys).some(Boolean)), 'focus loss pauses and clears held desktop input');
  await desktop.reload(); await desktop.waitForFunction(() => $('menu').classList.contains('on'));
  check(await desktop.evaluate(() => G.set.battleSize === '5' && G.set.quality === 'low' && G.set.motion === .6 && G.set.sens === 1.35 && $('sQuality').value === 'low'), 'squad size and existing/new settings survive reload');
  checks.push(...await desktop.evaluate(() => {
    const out = [], yes = (v, n) => { if (!v) throw Error(n); out.push(n); }; G.noLock = true;
    for (const mode of ['comp', 'dm', 'range']) for (const size of [5, 8, 12]) { G.mode = mode; G.set.battleSize = String(size); startMatch(); const blue = G.ents.filter(e => e.team === 'blue').length, red = G.ents.filter(e => e.team === 'red').length; yes(mode === 'range' ? G.bots.length === 5 && blue === 1 && red === 5 : blue === size && red === size && G.bots.length === 2 * size - 1, `${mode} roster at selected ${size}v${size}`); }
    G.mode = 'comp'; G.set.battleSize = 'auto'; G.set.autoTeamSize = 8; startMatch(); G.state = 'live'; G.manualStep = false;
    for (let i = 0; i < 299; i++) samplePerformance(20, 22); yes(G.perf.pending === null, 'auto roster waits for 300 samples before the time window'); samplePerformance(20, 22); yes(G.perf.pending === 5 && G.teamSize === 8 && G.bots.length === 15, 'slow samples queue smaller roster without midround removal'); startRound(); yes(G.teamSize === 5 && G.bots.length === 9 && G.perf.pending === null, 'competitive roster change applies at next round boundary');
    G.state = 'live'; for (let i = 0; i < 300; i++) samplePerformance(16, 7); yes(G.perf.pending === 8 && G.teamSize === 5, 'fast samples queue larger roster without midround insertion'); startRound(); yes(G.teamSize === 8 && G.bots.length === 15, 'larger roster applies at next round boundary');
    G.state = 'live'; for (let i = 0; i < 300; i++) samplePerformance(23, 12); yes(G.perf.pending === null && G.teamSize === 8, 'middle performance range keeps current roster'); const n = G.perf.samples.length; G.paused = true; for (let i = 0; i < 10; i++) samplePerformance(35, 22); G.paused = false; samplePerformance(.5, 0); yes(G.perf.samples.length === n, 'pause and submillisecond samples are excluded from auto sizing'); G.set.autoTeamSize = 8; startMatch(); G.state = 'live'; for (let i = 0; i < 29; i++) samplePerformance(300, 250); yes(G.perf.pending === null, 'time window still requires 30 valid samples'); samplePerformance(300, 250); yes(G.perf.pending === 5 && G.teamSize === 8, 'long frame stalls queue reduction through the time window'); G.perf.pending = null; G.set.autoTeamSize = 8;
    G.mode = 'dm'; startMatch(); G.state = 'live'; for (let i = 0; i < 300; i++) samplePerformance(35, 22); updateFlow(.016); yes(G.teamSize === 8 && G.perf.pending === 5, 'deathmatch keeps roster stable during current match'); startMatch(); yes(G.teamSize === 5 && G.bots.length === 9, 'deathmatch pending roster applies to next match');
    G.set.battleSize = '12'; startMatch(); G.state = 'live'; for (let i = 0; i < 300; i++) samplePerformance(35, 22); yes(G.teamSize === 12 && G.perf.pending === null, 'manual roster remains fixed under slow samples');
    G.mode = 'comp'; startMatch(); yes(G.bots.every(b => b.role && Number.isInteger(b.slot) && Number.isInteger(b.squad)) && new Set(G.bots.map(b => b.team + ':' + b.slot)).size === 23, '12v12 gives every bot a unique team slot and tactical role');
    G.state = 'live'; BOMB.state = 'planted'; BOMB.site = 'A'; BOMB.t = 30; BOMB.defuser = null; BOMB.pos.set(44, 0, -29); const defenders = G.bots.filter(b => b.team === 'blue'); for (const b of defenders) botObjective(b, G.now); yes(defenders.filter(b => b.intent === '回防拆核').length === 1 && defenders.filter(b => b.intent === '掩护拆核').length === defenders.length - 1, 'one nominated defuser and remaining guards respond to planted core');
    defenders.forEach((b, i) => { b.pos.set(BOMB.pos.x + (i === 0 ? 0 : i === 1 ? 3.5 : 25 + i), BOMB.pos.y, BOMB.pos.z); b.targetVis = i === 0; b.act = null; }); BOMB.defuser = defenders[0]; botObjective(defenders[0], G.now); botObjective(defenders[1], G.now); yes(defenders[0].intent === '掩护拆核' && defenders[1].intent === '回防拆核', 'interrupted defuser can hand off to available teammate');
    const ents = G.ents, shooter = makeEnt('blue', 'test shooter'), target = makeEnt('red', 'test target'), ally = makeEnt('blue', 'test ally'); shooter.alive = target.alive = ally.alive = true; shooter.pos.set(0, 0, 0); target.pos.set(0, 0, -10); ally.pos.set(0, 0, -5); G.ents = [shooter, target, ally]; yes(!botLineClear(shooter, target), 'friendly actor blocks bot firing lane'); ally.pos.x = 2; yes(botLineClear(shooter, target), 'bot firing lane clears when teammate moves aside'); G.ents = ents;
    const drawAll = () => { frame(0); scene.traverse(o => o.frustumCulled = false); renderer.render(scene, camera); }; startMatch(); drawAll(); startMatch(); drawAll(); const base = { geometries: renderer.info.memory.geometries, programs: renderer.info.programs.length, lines: LINE_MATS.length }; let disposed = true; for (let i = 0; i < 3; i++) { const old = G.bots.slice(); startMatch(); drawAll(); disposed = disposed && old.every(b => b.model === null); } const after = { geometries: renderer.info.memory.geometries, programs: renderer.info.programs.length, lines: LINE_MATS.length }; if (!disposed || JSON.stringify(base) !== JSON.stringify(after)) throw Error('model resource mismatch ' + JSON.stringify({ disposed, base, after })); yes(true, 'repeated 12v12 restart disposes old models with stable GPU geometry and shader counts'); return out;
  })); await desktop.close();
  const mobile = await openPage(url + '/?touch', { viewport: { width: 844, height: 390 }, isMobile: true, hasTouch: true });
  checks.push(...await mobile.evaluate(() => {
    const out = [], yes = (v, n) => { if (!v) throw Error(n); out.push(n); }, ev = (type, id, x, y, target) => { const t = new Touch({ identifier: id, target, clientX: x, clientY: y }); target.dispatchEvent(new TouchEvent(type, { bubbles: true, cancelable: true, changedTouches: [t], touches: type === 'touchend' ? [] : [t], targetTouches: [t] })); };
    G.mode = 'comp'; startMatch(); yes(G.teamSize === 5, 'fresh mobile auto roster starts conservatively at 5v5'); G.mode = 'range'; startMatch(); G.set.autoFire = false; const L = $('touch'), f = $('tFire'), f2 = $('tFire2');
    ev('touchstart', 1, 760, 280, f); ev('touchstart', 2, 40, 200, f2); ev('touchend', 2, 40, 200, f2); yes(G.fire && TOUCH.btns.size === 1, 'releasing one touch fire preserves another held fire'); ev('touchend', 1, 760, 280, f); yes(!G.fire && !TOUCH.btns.size, 'last fire release clears fire');
    ev('touchstart', 3, 80, 290, L); ev('touchmove', 3, 83, 292, L); yes(!TOUCH.move.x && !TOUCH.move.y, 'joystick deadzone filters thumb drift'); ev('touchmove', 3, 138, 290, L); yes(TOUCH.move.x === 1, 'joystick full travel stays available'); ev('touchstart', 4, 760, 280, f); ev('touchcancel', 4, 760, 280, f); yes(!G.fire && !TOUCH.joy && !TOUCH.btns.size && !TOUCH.move.x, 'touch cancellation resets held controls');
    G.set.touchAccel = false; TOUCH.aimOn = false; G.player.yaw = 0; ev('touchstart', 6, 450, 200, L); ev('touchmove', 6, 490, 200, L); ev('touchend', 6, 490, 200, L); const yaw = G.player.yaw; G.player.yaw = 0; ev('touchstart', 7, 450, 200, L); for (let x = 460; x <= 490; x += 10) ev('touchmove', 7, x, 200, L); ev('touchend', 7, 490, 200, L); yes(Math.abs(yaw - G.player.yaw) < 1e-10, 'linear aim is independent of touch event grouping');
    const oe = G.ents, ore = rayEnt, orw = rayWorld, osb = smokeBlocks; G.ents = [{ alive: true, team: 'red' }]; rayEnt = () => ({ t: 20 }); rayWorld = () => null; smokeBlocks = () => true; G.set.autoFire = true; TOUCH.aimCheck = 0; updateTouch(.5); yes(!TOUCH.aimOn && !G.fire, 'smoke blocks auto aim acquisition'); smokeBlocks = () => false; G.flashT = 1; TOUCH.aimCheck = 0; updateTouch(.5); yes(!TOUCH.aimOn && !G.fire, 'flash blindness blocks auto aim acquisition'); G.flashT = 0; TOUCH.aimCheck = 0; updateTouch(.5); yes(TOUCH.auto && G.fire, 'visible acquired target enables autofire'); G.player.cur = 'he'; updateTouch(.1); yes(!TOUCH.auto && !G.fire && !G.fireEdge, 'grenade switch clears automatic fire'); G.ents = oe; rayEnt = ore; rayWorld = orw; smokeBlocks = osb;
    G.set.layout = { tFire: [1, 1], tFire2: [0, 0] }; G.set.btnScale = 1.6; layoutEdit(true); const r = f.getBoundingClientRect(), r2 = f2.getBoundingClientRect(); yes(r.right <= innerWidth - 7.9 && r.bottom <= innerHeight - 7.9 && r2.left >= 7.9 && r2.top >= 7.9, 'scaled saved controls stay in viewport'); const cx = r.x + r.width / 2, cy = r.y + r.height / 2; ev('touchstart', 10, cx, cy, f); ev('touchmove', 10, cx - 70, cy - 40, f); let moved = f.getBoundingClientRect(); yes(Math.abs(moved.x - (r.x - 70)) < .1, 'scaled layout dragging does not jump'); ev('touchend', 11, 0, 0, L); ev('touchmove', 10, cx - 100, cy - 60, f); moved = f.getBoundingClientRect(); yes(Math.abs(moved.x - (r.x - 100)) < .1, 'another finger release does not end layout drag'); ev('touchend', 10, cx - 100, cy - 60, f); layoutEdit(false); return out;
  }));
  const before = await mobile.evaluate(() => { const b = document.querySelector('#pause .box'); b.scrollTop = 0; return { top: b.scrollTop, overflow: b.scrollHeight > b.clientHeight }; });
  const cdp = await mobile.context().newCDPSession(mobile); await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 410, y: 315 }] }); for (let i = 1; i <= 10; i++) { await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 410, y: 315 - i * 20 }] }); await mobile.waitForTimeout(16); } await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await mobile.waitForTimeout(100);
  check(!before.overflow || await mobile.evaluate(() => document.querySelector('#pause .box').scrollTop > 0), 'landscape pause settings scroll with a real touch pan'); await capture(mobile, 'mobile-pause');
  await mobile.setViewportSize({ width: 390, height: 844 }); await mobile.waitForTimeout(100); check(await mobile.evaluate(() => $('rotate').classList.contains('on') && document.documentElement.scrollWidth === innerWidth && !G.fire && !TOUCH.move.x), 'portrait orientation prompt covers gameplay and clears input without overflow'); await capture(mobile, 'mobile-portrait');
  await mobile.setViewportSize({ width: 844, height: 390 }); await mobile.waitForTimeout(100); check(await mobile.evaluate(() => !$('rotate').classList.contains('on')), 'landscape rotation removes orientation prompt'); await mobile.close();
  check(errors.length === 0, 'no console or page errors'); console.log(JSON.stringify({ checks, notes, errors }, null, 2)); console.log('\nUPGRADE CHECK OK');
})().catch(e => { console.error('\nUPGRADE CHECK FAIL\n' + e.stack); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); server.close(); });
